## 03_merge_and_dedup

In [1]:
import pandas as pd

In [2]:
df_a = pd.read_csv(
    "../data/interim/hubspot_a_standardized.csv",
    parse_dates=["created_date", "mql_date", "sql_date", "opportunity_date", "customer_date"]
)

df_b = pd.read_csv(
    "../data/interim/hubspot_b_standardized.csv",
    parse_dates=["created_date", "mql_date", "sql_date", "opportunity_date", "customer_date"]
)

print("A shape:", df_a.shape)
print("B shape:", df_b.shape)

A shape: (36, 17)
B shape: (36, 17)

In [3]:
df_a

,lead_id,email,first_name,last_name,company,job_title,source,lifecycle_stage,created_date,mql_date,sql_date,opportunity_date,customer_date,owner,notes,last_updated,source_system
0,A-10031,leo.cox@acornchildcare.com,Leo,Cox,Acorn Childcare,Founder,Trade Show,Lead,2024-01-26,NaT,NaT,NaT,NaT,Priya Nair,owner changed after routing,2024-03-29,hubspot_A
1,A-10001,liam.brooks@nexahealth.io,Liam,Brooks,NexaHealth,Operations Manager,Referral,Opportunity,2024-02-02,2024-02-14,2024-03-02,2024-03-06,NaT,Tina Shah,owner changed after routing,2024-03-06,hubspot_A
2,A-10009,mia.flores@northwindadvisors.com,Mia,Flores,North Wind Advisors,Director of Finance,Direct Traffic,Opportunity,2024-02-02,2024-02-04,2024-03-07,2024-03-22,NaT,Priya Nair,Jordan updated stage after call,2024-05-15,hubspot_A
3,A-10026,hannah.graham@meridianvet.com,Hannah,Graham,Meridian Veterinary,Practice Manager,Paid Search,Lead,2024-02-09,NaT,NaT,NaT,NaT,Marcus Lee,MQL date added later,2024-02-14,hubspot_A
4,A-10003,emma.diaz@pioneerlogistics.com,Emma,Diaz,Pioneer Logistics LLC,VP People,Direct Traffic,Opportunity,2024-02-18,NaT,2024-03-03,2024-04-15,NaT,Jordan Miles,MQL date added later,2024-05-15,hubspot_A
5,A-10012,james.bailey@clearwavedental.com,James,Bailey,Clear Wave Dental,Practice Administrator,Paid Search,SQL,2024-02-21,2024-03-09,2024-03-09,NaT,NaT,Priya Nair,entered manually by marketing,2024-02-21,hubspot_A
6,A-10020,jackhughes@novastaffing.com,Jack,Hughes,Nova Staffing,Sales Director,Partner,Lead,2024-02-22,NaT,NaT,NaT,NaT,Sofia Gomez,possible duplicate from legacy CRM,2024-04-16,hubspot_A
7,A-10005,elijah.turner@mapleworksmfg.com,Elijah,Turner,MapleWorks Manufacturing,People Ops Manager,Organic Search,Opportunity,2024-04-18,2024-04-27,2024-05-29,2024-07-06,NaT,Jordan Miles,possible duplicate from legacy CRM,2024-08-14,hubspot_A
8,A-10011,amelia.ward@greenlineenergy.com,Amelia,Ward,Greenline Energy,HR Director,Direct Traffic,NaN,2024-04-21,2024-04-27,NaT,NaT,NaT,Ben Carter,possible duplicate from legacy CRM,2024-05-03,hubspot_A
9,A-10004,olivia.chen@harborfg.com,Olivia,Chen,Harbor Financial Grp,Recruiting Lead,Direct Traffic,SQL,2024-04-27,2024-05-14,2024-05-31,NaT,NaT,Tina Shah,MQL date added later,2024-06-30,hubspot_A
10,A-10033,penelope.stewart@cloudnine-tech.io,Penelope,Stewart,CloudNine Tech,Director People,Direct Traffic,NaN,2024-05-04,2024-05-29,NaT,NaT,NaT,Sofia Gomez,MQL date added later,2024-08-26,hubspot_A
11,A-10002,noah.reed@stonebridgehr.com,Noah,Reed,Stonebridge HR,HR Director,Partner,MQL,2024-05-22,2024-06-08,NaT,NaT,NaT,Priya Nair,Jordan updated stage after call,2024-06-02,hubspot_A
12,A-10023,matthew.russell@elmstreetfoods.com,Matthew,Russell,Elm Street Foods,HR Manager,Paid Search,Opportunity,2024-08-30,2024-09-24,2024-10-05,2024-10-31,NaT,Sofia Gomez,imported from webinar list,2024-09-12,hubspot_A
13,A-10000,ava.patel@brightpathco.com,Ava,Patel,Bright Path Consulting,Consultant,Direct Traffic,Lead,2024-09-07,NaT,NaT,NaT,NaT,Jordan Miles,NaN,2024-10-06,hubspot_A
14,A-10025,david.fisher@peakpointroofing.com,David,Fisher,PeakPoint Roofing,Operations Director,Paid Search,Opportunity,2024-10-12,2024-11-05,2024-11-22,2024-12-14,NaT,Ben Carter,imported from webinar list,2024-11-14,hubspot_A
15,A-10028,samuel.myers@corelinepackaging.com,Samuel,Myers,Coreline Packaging,Finance Director,Partner,SQL,2024-11-03,2024-11-24,2024-12-20,NaT,NaT,Ben Carter,Jordan updated stage after call,2024-12-11,hubspot_A
16,A-10006,sophia.james@bluepeaksoft.com,Sophia,James,Blue Peak Software,HRBP,Partner,Opportunity,2025-01-06,2025-01-31,2025-02-19,2025-03-06,NaT,Tina Shah,NaN,2025-01-22,hubspot_A
17,A-10022,victoria.simmons@silverlaketelecom.com,Victoria,Simmons,SilverLake Telecom,Comp & Benefits Manager,Trade Show,Customer,2025-01-08,NaT,2025-02-04,2025-02-26,2025-03-14,Tina Shah,MQL date added later,2025-05-06,hubspot_A
18,A-10024,luna.butler@crownmedsupply.com,Luna,Butler,Crown Medical Supply,Recruiting Manager,Paid Search,Opportunity,2025-01-26,2025-02-10,2025-02-24,2025-03-08,NaT,Priya Nair,owner changed after routing,2025-03-09,hubspot_A
19,A-10013,harperbennett@solsticehotels.com,Harper,Bennett,Solstice Hospitality,Regional HR Manager,Paid Search,NaN,2025-02-03,2025-02-28,NaT,NaT,NaT,Jordan Miles,imported from webinar list,2025-04-18,hubspot_A
20,A-10032,julian.parker@westfieldtherapy.com,Julian,Parker,Westfield Therapy,Clinic Administrator,Partner,MQL,2025-02-13,2025-03-05,NaT,NaT,NaT,Tina Shah,entered manually by marketing,2025-06-10,hubspot_A
21,A-10029,nora.hayes@bridgewellfinance.com,Nora,Hayes,Bridgewell Finance,HR Director,Referral,SQL,2025-02-19,2025-02-19,2025-03-10,NaT,NaT,Sofia Gomez,possible duplicate from legacy CRM,2025-03-18,hubspot_A
22,A-10010,ethan.price@vertexbuildgrp.com,Ethan,Price,Vertex Build Group,Talent Manager,Referral,NaN,2025-02-20,2025-02-23,NaT,NaT,NaT,Sofia Gomez,entered manually by marketing,2025-04-04,hubspot_A
23,A-10027,joseph.hamilton@trailheadoutdoor.co,Joseph,Hamilton,Trailhead Outdoor Co,People Director,Direct Traffic,Lead,2025-03-22,NaT,NaT,NaT,NaT,Jordan Miles,owner changed after routing,2025-06-22,hubspot_A
24,A-10018,scarlett.long@heliomedia.co,Scarlett,Long,Helio Media,Revenue Operations Manager,Organic Search,Opportunity,2025-03-24,2025-04-15,2025-05-04,2025-06-12,NaT,Jordan Miles,imported from webinar list,2025-06-27,hubspot_A
25,A-10008,isabellakelly@summitretailpartners.com,Isabella,Kelly,Summit Retail Partners,VP HR,Organic Search,Customer,2025-03-24,NaT,2025-04-14,2025-04-29,2025-05-16,Tina Shah,owner changed after routing,2025-04-01,hubspot_A
26,A-10017,ella.sanders@beaconbiotech.com,Ella,Sanders,Beacon Biotech,HR Lead,Webinar,NaN,2025-04-14,2025-05-02,2025-05-08,NaT,NaT,Marcus Lee,Jordan updated stage after call,2025-05-04,hubspot_A
27,A-10034,riley.peterson@harborlinetransit.com,Riley,Peterson,Harborline Transit,Safety Director,Trade Show,NaN,2025-05-31,2025-06-17,NaT,NaT,NaT,Marcus Lee,NaN,2025-09-06,hubspot_A
28,A-10030,zoey.cole@urbansparkcreative.com,Zoey,Cole,UrbanSpark Creative,Office Manager,Direct Traffic,SQL,2025-06-07,2025-07-02,2025-07-12,NaT,NaT,Tina Shah,Jordan updated stage after call,2025-06-25,hubspot_A
29,A-10035,levi.reed@metrobuildservices.com,Levi,Reed,MetroBuild Services,HR Director,Paid Search,SQL,2025-06-17,2025-06-24,2025-07-11,NaT,NaT,Tina Shah,Jordan updated stage after call,2025-08-05,hubspot_A
30,A-10016,abigail.morgan@redoakconstruction.com,Abigail,Morgan,Red Oak Construction,HR Manager,Webinar,MQL,2025-06-19,2025-06-27,NaT,NaT,NaT,Jordan Miles,possible duplicate from legacy CRM,2025-06-20,hubspot_A
31,A-10014,benjamincook@riverstonelegal.com,Benjamin,Cook,Riverstone Legal,Office Manager,Organic Search,Lead,2025-07-09,NaT,NaT,NaT,NaT,Tina Shah,MQL date added later,2025-07-17,hubspot_A
32,A-10019,grace.perry@primestonerealty.com,Grace,Perry,PrimeStone Realty,COO,Referral,Lead,2025-07-20,NaT,NaT,NaT,NaT,Marcus Lee,MQL date added later,2025-11-12,hubspot_A
33,A-10021,chloe.foster@truenorthlabs.ai,Chloe,Foster,TrueNorth Labs,People Ops Specialist,Paid Search,Lead,2025-07-28,NaT,NaT,NaT,NaT,Jordan Miles,possible duplicate from legacy CRM,2025-09-05,hubspot_A
34,A-10015,henry.ross@copperlinesecurity.com,Henry,Ross,Copperline Security,COO,Trade Show,Lead,2025-09-01,NaT,NaT,NaT,NaT,Ben Carter,possible duplicate from legacy CRM,2025-11-12,hubspot_A
35,A-10007,mason.clark@everwellclinics.com,Mason,Clark,Everwell Clinics,Controller,Trade Show,NaN,2025-11-06,2025-11-23,2025-12-03,NaT,NaT,Sofia Gomez,possible duplicate from legacy CRM,2025-12-23,hubspot_A

In [4]:
df_b

,lead_id,email,first_name,last_name,company,job_title,source,lifecycle_stage,created_date,mql_date,sql_date,opportunity_date,customer_date,owner,notes,last_updated,source_system
0,B-20001,noah.reed@stonebridgehr.com,Noah,Reed,Stone Bridge HR,HR Director,Outbound SDR,Customer,2024-02-07,2024-02-16,2024-02-13,2024-04-06,2024-05-13,Tina Shah,needs review,2024-03-10,hubspot_B
1,B-20004,elijah.turner@mapleworksmfg.com,Elijah,Turner,MapleWorks Manufacturing,People Ops Manager,Paid Social,SQL,2024-02-21,2024-02-28,2024-03-07,NaT,NaT,Marcus Lee,manually entered,2024-02-27,hubspot_B
2,B-20028,samuel.myers+coadv@corelinepackaging.com,Samuel,Myers,Coreline Packaging,Finance Director,Direct,Lead,2024-03-01,NaT,NaT,NaT,NaT,Priya Nair,NaN,2024-05-01,hubspot_B
3,B-20025,hannah.graham@meridianvet.com,Hannah,Graham,Meridian Veterinary,Practice Manager,Direct,MQL,2024-03-16,2024-03-31,NaT,NaT,NaT,Priya Nair,manually entered,2024-07-28,hubspot_B
4,B-20034,wyatt.morris@cedarstonehospitality.com,Wyatt,Morris,Cedarstone Hospitality,Regional GM,Event,Lead,2024-04-18,NaT,NaT,NaT,NaT,Sofia Gomez,stage synced late,2024-06-24,hubspot_B
5,B-20009,amelia.ward@greenlineenergy.com,Amelia,Ward,Green Line Energy,HR Director,Outbound SDR,MQL,2024-04-28,2024-05-11,NaT,NaT,NaT,Tina Shah,duplicate suspected,2024-07-31,hubspot_B
6,B-20022,victoria.simmons@silverlaketelecom.com,Victoria,Simmons,SilverLake Telecom,Comp & Benefits Manager,Direct,MQL,2024-05-06,2024-05-09,NaT,NaT,NaT,Priya Nair,needs review,2024-07-07,hubspot_B
7,B-20024,david.fisher@peakpointroofing.com,David,Fisher,PeakPoint Roofing,Operations Director,Partner,MQL,2024-07-02,2024-07-17,NaT,NaT,NaT,Priya Nair,marketing updated after event,2024-10-15,hubspot_B
8,B-20013,abigail.morgan@redoakconstruction.com,Abigail,Morgan,RedOak Construction,HR Manager,Direct,Lead,2024-07-05,NaT,NaT,NaT,NaT,Ben Carter,needs review,2024-10-28,hubspot_B
9,B-20000,liam.brooks@nexahealth.io,Liam,Brooks,Nexa Health,Operations Manager,Direct,Opportunity,2024-07-06,2024-07-08,2024-08-03,2024-08-29,NaT,Ben Carter,needs review,2024-11-05,hubspot_B
10,B-20015,daniel.bryant@orbitfreight.com,Daniel,Bryant,Orbit Freight,Director HRIS,organic,Lead,2024-07-10,NaT,NaT,NaT,NaT,Sofia Gomez,marketing updated after event,2024-09-15,hubspot_B
11,B-20033,julian.parker@westfieldtherapy.com,Julian,Parker,Westfield Therapy,Clinic Administrator,Outbound SDR,Lead,2024-08-24,NaT,NaT,NaT,NaT,Marcus Lee,manually entered,2024-12-21,hubspot_B
12,B-20011,benjamin.cook@riverstonelegal.com,Benjamin,Cook,Riverstone Legal,Office Manager,Partner,Opportunity,2024-09-09,2024-09-17,2024-10-20,2024-11-27,NaT,Marcus Lee,stage synced late,2024-10-11,hubspot_B
13,B-20018,scarlett.long@heliomedia.co,Scarlett,Long,Helio Media,Revenue Operations Manager,Outbound SDR,Customer,2024-09-22,2024-10-10,2024-10-11,2024-11-23,2025-01-17,Priya Nair,manually entered,2025-01-20,hubspot_B
14,B-20031,zoey.cole@urbansparkcreative.com,Zoey,Cole,UrbanSpark Creative,Office Manager,Outbound SDR,Lead,2024-11-08,NaT,NaT,NaT,NaT,Sofia Gomez,stage synced late,2024-12-13,hubspot_B
15,B-20005,sophia.james@bluepeaksoft.com,Sophia,James,BluePeak Software,HRBP,Partner,SQL,2024-12-16,2024-12-28,2025-01-22,NaT,NaT,Jordan Miles,duplicate suspected,2025-05-01,hubspot_B
16,B-20020,jack.hughes@novastaffing.com,Jack,Hughes,Nova Staffing,Sales Director,Direct,Lead,2024-12-28,NaT,NaT,NaT,NaT,Jordan Miles,marketing updated after event,2025-03-06,hubspot_B
17,B-20008,ethan.price@vertexbuildgrp.com,Ethan,Price,VertexBuild Group,Talent Manager,Partner,Lead,2025-01-10,NaT,NaT,NaT,NaT,Jordan Miles,NaN,2025-02-27,hubspot_B
18,B-20019,sebastian.powell@wellrootrx.com,Sebastian,Powell,WellRoot Pharmacy,HRBP,referral,MQL,2025-01-22,2025-02-01,NaT,NaT,NaT,Jordan Miles,duplicate suspected,2025-03-27,hubspot_B
19,B-20027,layla.ford@unitybehavioral.org,Layla,Ford,Unity Behavioral Health,HRIS Analyst,referral,Customer,2025-02-24,2025-03-16,2025-04-16,2025-05-20,2025-05-25,Tina Shah,stage synced late,2025-05-11,hubspot_B
20,B-20003,olivia.chen@harborfg.com,Olivia,Chen,Harbor Financial Group,Recruiting Lead,Direct,MQL,2025-04-07,2025-04-09,NaT,NaT,NaT,Jordan Miles,marketing updated after event,2025-05-28,hubspot_B
21,B-20006,mason.clark@everwellclinics.com,Mason,Clark,Everwell Clinic,Controller,referral,SQL,2025-04-14,NaT,2025-05-18,NaT,NaT,Tina Shah,stage synced late,2025-08-25,hubspot_B
22,B-20017,michael.barnes@oakridenp.org,Michael,Barnes,Oakridge Nonprofit,Finance Manager,Partner,Lead,2025-04-25,NaT,NaT,NaT,NaT,Marcus Lee,manually entered,2025-05-18,hubspot_B
23,B-20014,emily.watson@firstharborbank.com,Emily,Watson,First Harbor Bank,SVP Talent,Paid Social,MQL,2025-04-29,2025-05-17,NaT,NaT,NaT,Tina Shah,marketing updated after event,2025-05-18,hubspot_B
24,B-20023,matthew.russell@elmstreetfoods.com,Matthew,Russell,Elm Street Foods,HR Manager,Event,SQL,2025-05-13,2025-05-25,2025-06-06,NaT,NaT,Sofia Gomez,duplicate suspected,2025-09-15,hubspot_B
25,B-20026,joseph.hamilton@trailheadoutdoor.co,Joseph,Hamilton,Trailhead Outdoor Co,People Director,Outbound SDR,Lead,2025-05-13,NaT,NaT,NaT,NaT,Jordan Miles,duplicate suspected,2025-09-26,hubspot_B
26,B-20010,harper.bennett@solsticehotels.com,Harper,Bennett,Solstice Hospitality,Regional HR Manager,Direct,SQL,2025-05-30,2025-06-10,2025-07-07,NaT,NaT,Sofia Gomez,marketing updated after event,2025-07-18,hubspot_B
27,B-20029,nora.hayes@bridgewellfinance.com,Nora,Hayes,Bridgewell Finance,HR Director,organic,Customer,2025-06-24,2025-06-28,2025-07-12,2025-08-10,2025-09-22,Priya Nair,duplicate suspected,2025-09-08,hubspot_B
28,B-20021,owen.coleman@atlasautogroup.com,Owen,Coleman,Atlas Auto Group,GM,Event,Lead,2025-08-16,NaT,NaT,NaT,NaT,Ben Carter,manually entered,2025-11-28,hubspot_B
29,B-20035,riley.peterson@harborlinetransit.com,Riley,Peterson,Harborline Transit,Safety Director,Outbound SDR,MQL,2025-09-21,NaT,NaT,NaT,NaT,Jordan Miles,stage synced late,2026-01-17,hubspot_B
30,B-20002,emma.diaz@pioneerlogistics.com,Emma,Diaz,Pioneer Logistics LLC,VP People,Event,SQL,2025-10-30,2025-11-11,2025-11-12,NaT,NaT,Marcus Lee,needs review,2026-01-09,hubspot_B
31,B-20016,ella.sanders@beaconbiotech.com,Ella,Sanders,Beacon Biotech,HR Lead,Direct,SQL,2025-11-02,2025-11-27,2025-12-09,NaT,NaT,Marcus Lee,NaN,2026-01-14,hubspot_B
32,B-20032,leo.cox@acornchildcare.com,Leo,Cox,Acorn Childcare,Founder,Event,Lead,2025-11-05,NaT,NaT,NaT,NaT,Sofia Gomez,needs review,2025-12-19,hubspot_B
33,B-20012,henry.ross+coadv@copperlinesecurity.com,Henry,Ross,Copper Line Security,COO,referral,Opportunity,2025-11-15,2025-11-30,2025-12-06,2025-12-06,NaT,Jordan Miles,NaN,2025-11-28,hubspot_B
34,B-20030,aiden.west@shorelinefoods.com,Aiden,West,Shoreline Foods,VP Operations,Outbound SDR,Customer,2025-11-16,NaT,2025-12-24,2026-01-22,2026-03-20,Marcus Lee,manually entered,2026-02-25,hubspot_B
35,B-20007,isabella.kelly@summitretailpartners.com,Isabella,Kelly,Summit Retail,VP HR,Paid Social,MQL,2025-11-28,2025-12-23,NaT,NaT,NaT,Priya Nair,NaN,2026-03-05,hubspot_B

In [5]:
df_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   lead_id           36 non-null     object
 1   email             36 non-null     object
 2   first_name        36 non-null     object
 3   last_name         36 non-null     object
 4   company           36 non-null     object
 5   job_title         36 non-null     object
 6   source            36 non-null     object
 7   lifecycle_stage   29 non-null     object
 8   created_date      36 non-null     datetime64[ns]
 9   mql_date          24 non-null     datetime64[ns]
 10  sql_date          19 non-null     datetime64[ns]
 11  opportunity_date  11 non-null     datetime64[ns]
 12  customer_date     2 non-null      datetime64[ns]
 13  owner             36 non-null     object
 14  notes             33 non-null     object
 15  last_updated      36 non-null     object
 16  source_system     36 non-null     object
dtypes: datetime64[ns](5), object(12)
memory usage: 4.9+ KB

In [6]:
df_b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   lead_id           36 non-null     object
 1   email             36 non-null     object
 2   first_name        36 non-null     object
 3   last_name         36 non-null     object
 4   company           36 non-null     object
 5   job_title         36 non-null     object
 6   source            36 non-null     object
 7   lifecycle_stage   36 non-null     object
 8   created_date      36 non-null     datetime64[ns]
 9   mql_date          21 non-null     datetime64[ns]
 10  sql_date          15 non-null     datetime64[ns]
 11  opportunity_date  8 non-null      datetime64[ns]
 12  customer_date     5 non-null      datetime64[ns]
 13  owner             36 non-null     object
 14  notes             31 non-null     object
 15  last_updated      36 non-null     object
 16  source_system     36 non-null     object
dtypes: datetime64[ns](5), object(12)
memory usage: 4.9+ KB

In [7]:
df_all = pd.concat([df_a, df_b], ignore_index=True)

print("Combined shape:", df_all.shape)
df_all

Combined shape: (72, 17)

,lead_id,email,first_name,last_name,company,job_title,source,lifecycle_stage,created_date,mql_date,sql_date,opportunity_date,customer_date,owner,notes,last_updated,source_system
0,A-10031,leo.cox@acornchildcare.com,Leo,Cox,Acorn Childcare,Founder,Trade Show,Lead,2024-01-26,NaT,NaT,NaT,NaT,Priya Nair,owner changed after routing,2024-03-29,hubspot_A
1,A-10001,liam.brooks@nexahealth.io,Liam,Brooks,NexaHealth,Operations Manager,Referral,Opportunity,2024-02-02,2024-02-14,2024-03-02,2024-03-06,NaT,Tina Shah,owner changed after routing,2024-03-06,hubspot_A
2,A-10009,mia.flores@northwindadvisors.com,Mia,Flores,North Wind Advisors,Director of Finance,Direct Traffic,Opportunity,2024-02-02,2024-02-04,2024-03-07,2024-03-22,NaT,Priya Nair,Jordan updated stage after call,2024-05-15,hubspot_A
3,A-10026,hannah.graham@meridianvet.com,Hannah,Graham,Meridian Veterinary,Practice Manager,Paid Search,Lead,2024-02-09,NaT,NaT,NaT,NaT,Marcus Lee,MQL date added later,2024-02-14,hubspot_A
4,A-10003,emma.diaz@pioneerlogistics.com,Emma,Diaz,Pioneer Logistics LLC,VP People,Direct Traffic,Opportunity,2024-02-18,NaT,2024-03-03,2024-04-15,NaT,Jordan Miles,MQL date added later,2024-05-15,hubspot_A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,B-20016,ella.sanders@beaconbiotech.com,Ella,Sanders,Beacon Biotech,HR Lead,Direct,SQL,2025-11-02,2025-11-27,2025-12-09,NaT,NaT,Marcus Lee,NaN,2026-01-14,hubspot_B
68,B-20032,leo.cox@acornchildcare.com,Leo,Cox,Acorn Childcare,Founder,Event,Lead,2025-11-05,NaT,NaT,NaT,NaT,Sofia Gomez,needs review,2025-12-19,hubspot_B
69,B-20012,henry.ross+coadv@copperlinesecurity.com,Henry,Ross,Copper Line Security,COO,referral,Opportunity,2025-11-15,2025-11-30,2025-12-06,2025-12-06,NaT,Jordan Miles,NaN,2025-11-28,hubspot_B
70,B-20030,aiden.west@shorelinefoods.com,Aiden,West,Shoreline Foods,VP Operations,Outbound SDR,Customer,2025-11-16,NaT,2025-12-24,2026-01-22,2026-03-20,Marcus Lee,manually entered,2026-02-25,hubspot_B
71,B-20007,isabella.kelly@summitretailpartners.com,Isabella,Kelly,Summit Retail,VP HR,Paid Social,MQL,2025-11-28,2025-12-23,NaT,NaT,NaT,Priya Nair,NaN,2026-03-05,hubspot_B

In [8]:
# Fix lifecycle_stage BEFORE any further logic
df_all['lifecycle_stage'] = df_all['lifecycle_stage'].astype(str).str.strip()

stage_mapping = {
    'Lead': 'Lead',
    'lead': 'Lead',
    'MQL': 'MQL',
    'mql': 'MQL',
    'Marketing Qualified': 'MQL',
    'Marketing Qualified Lead': 'MQL',
    'SQL': 'SQL',
    'sql': 'SQL',
    'Sales Qualified': 'SQL',
    'SAL': 'SQL',
    'Opportunity': 'Opportunity',
    'Oppty': 'Opportunity',
    'Customer': 'Customer',
    'Closed Won': 'Customer',
    'Subscriber': 'Lead',
    'nan': None
}

df_all['lifecycle_stage'] = df_all['lifecycle_stage'].map(stage_mapping)

In [9]:
df_all['lifecycle_stage'].isna().sum()

7

In [10]:
duplicate_email_counts = df_all['email'].value_counts()
duplicate_email_counts[duplicate_email_counts > 1]

leo.cox@acornchildcare.com                2
david.fisher@peakpointroofing.com         2
abigail.morgan@redoakconstruction.com     2
zoey.cole@urbansparkcreative.com          2
riley.peterson@harborlinetransit.com      2
ella.sanders@beaconbiotech.com            2
liam.brooks@nexahealth.io                 2
scarlett.long@heliomedia.co               2
joseph.hamilton@trailheadoutdoor.co       2
ethan.price@vertexbuildgrp.com            2
nora.hayes@bridgewellfinance.com          2
julian.parker@westfieldtherapy.com        2
mason.clark@everwellclinics.com           2
sophia.james@bluepeaksoft.com             2
victoria.simmons@silverlaketelecom.com    2
hannah.graham@meridianvet.com             2
matthew.russell@elmstreetfoods.com        2
noah.reed@stonebridgehr.com               2
olivia.chen@harborfg.com                  2
amelia.ward@greenlineenergy.com           2
elijah.turner@mapleworksmfg.com           2
emma.diaz@pioneerlogistics.com            2
Name: email, dtype: int64

In [11]:
df_all[df_all['email'].isin(duplicate_email_counts[duplicate_email_counts > 1].index)] \
    .sort_values(['email', 'created_date']) \
    [['lead_id', 'email', 'company', 'lifecycle_stage', 'created_date', 'source_system']]

,lead_id,email,company,lifecycle_stage,created_date,source_system
44,B-20013,abigail.morgan@redoakconstruction.com,RedOak Construction,Lead,2024-07-05,hubspot_B
30,A-10016,abigail.morgan@redoakconstruction.com,Red Oak Construction,MQL,2025-06-19,hubspot_A
8,A-10011,amelia.ward@greenlineenergy.com,Greenline Energy,None,2024-04-21,hubspot_A
41,B-20009,amelia.ward@greenlineenergy.com,Green Line Energy,MQL,2024-04-28,hubspot_B
43,B-20024,david.fisher@peakpointroofing.com,PeakPoint Roofing,MQL,2024-07-02,hubspot_B
14,A-10025,david.fisher@peakpointroofing.com,PeakPoint Roofing,Opportunity,2024-10-12,hubspot_A
37,B-20004,elijah.turner@mapleworksmfg.com,MapleWorks Manufacturing,SQL,2024-02-21,hubspot_B
7,A-10005,elijah.turner@mapleworksmfg.com,MapleWorks Manufacturing,Opportunity,2024-04-18,hubspot_A
26,A-10017,ella.sanders@beaconbiotech.com,Beacon Biotech,None,2025-04-14,hubspot_A
67,B-20016,ella.sanders@beaconbiotech.com,Beacon Biotech,SQL,2025-11-02,hubspot_B
4,A-10003,emma.diaz@pioneerlogistics.com,Pioneer Logistics LLC,Opportunity,2024-02-18,hubspot_A
66,B-20002,emma.diaz@pioneerlogistics.com,Pioneer Logistics LLC,SQL,2025-10-30,hubspot_B
53,B-20008,ethan.price@vertexbuildgrp.com,VertexBuild Group,Lead,2025-01-10,hubspot_B
22,A-10010,ethan.price@vertexbuildgrp.com,Vertex Build Group,None,2025-02-20,hubspot_A
3,A-10026,hannah.graham@meridianvet.com,Meridian Veterinary,Lead,2024-02-09,hubspot_A
39,B-20025,hannah.graham@meridianvet.com,Meridian Veterinary,MQL,2024-03-16,hubspot_B
23,A-10027,joseph.hamilton@trailheadoutdoor.co,Trailhead Outdoor Co,Lead,2025-03-22,hubspot_A
61,B-20026,joseph.hamilton@trailheadoutdoor.co,Trailhead Outdoor Co,Lead,2025-05-13,hubspot_B
47,B-20033,julian.parker@westfieldtherapy.com,Westfield Therapy,Lead,2024-08-24,hubspot_B
20,A-10032,julian.parker@westfieldtherapy.com,Westfield Therapy,MQL,2025-02-13,hubspot_A
0,A-10031,leo.cox@acornchildcare.com,Acorn Childcare,Lead,2024-01-26,hubspot_A
68,B-20032,leo.cox@acornchildcare.com,Acorn Childcare,Lead,2025-11-05,hubspot_B
1,A-10001,liam.brooks@nexahealth.io,NexaHealth,Opportunity,2024-02-02,hubspot_A
45,B-20000,liam.brooks@nexahealth.io,Nexa Health,Opportunity,2024-07-06,hubspot_B
57,B-20006,mason.clark@everwellclinics.com,Everwell Clinic,SQL,2025-04-14,hubspot_B
35,A-10007,mason.clark@everwellclinics.com,Everwell Clinics,None,2025-11-06,hubspot_A
12,A-10023,matthew.russell@elmstreetfoods.com,Elm Street Foods,Opportunity,2024-08-30,hubspot_A
60,B-20023,matthew.russell@elmstreetfoods.com,Elm Street Foods,SQL,2025-05-13,hubspot_B
36,B-20001,noah.reed@stonebridgehr.com,Stone Bridge HR,Customer,2024-02-07,hubspot_B
11,A-10002,noah.reed@stonebridgehr.com,Stonebridge HR,MQL,2024-05-22,hubspot_A
21,A-10029,nora.hayes@bridgewellfinance.com,Bridgewell Finance,SQL,2025-02-19,hubspot_A
63,B-20029,nora.hayes@bridgewellfinance.com,Bridgewell Finance,Customer,2025-06-24,hubspot_B
9,A-10004,olivia.chen@harborfg.com,Harbor Financial Grp,SQL,2024-04-27,hubspot_A
56,B-20003,olivia.chen@harborfg.com,Harbor Financial Group,MQL,2025-04-07,hubspot_B
27,A-10034,riley.peterson@harborlinetransit.com,Harborline Transit,None,2025-05-31,hubspot_A
65,B-20035,riley.peterson@harborlinetransit.com,Harborline Transit,MQL,2025-09-21,hubspot_B
49,B-20018,scarlett.long@heliomedia.co,Helio Media,Customer,2024-09-22,hubspot_B
24,A-10018,scarlett.long@heliomedia.co,Helio Media,Opportunity,2025-03-24,hubspot_A
51,B-20005,sophia.james@bluepeaksoft.com,BluePeak Software,SQL,2024-12-16,hubspot_B
16,A-10006,sophia.james@bluepeaksoft.com,Blue Peak Software,Opportunity,2025-01-06,hubspot_A
42,B-20022,victoria.simmons@silverlaketelecom.com,SilverLake Telecom,MQL,2024-05-06,hubspot_B
17,A-10022,victoria.simmons@silverlaketelecom.com,SilverLake Telecom,Customer,2025-01-08,hubspot_A
50,B-20031,zoey.cole@urbansparkcreative.com,UrbanSpark Creative,Lead,2024-11-08,hubspot_B
28,A-10030,zoey.cole@urbansparkcreative.com,UrbanSpark Creative,SQL,2025-06-07,hubspot_A

In [12]:
df_all['email_base'] = df_all['email'].str.replace(r'\+[^@]+(?=@)', '', regex=True)

In [13]:
df_all['company_clean'] = (
    df_all['company']
    .str.lower()
    .str.strip()
    .str.replace(r'[^a-z0-9 ]', '', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
)

In [14]:
df_all['full_name_clean'] = (
    df_all['first_name'].str.lower().str.strip() + ' ' +
    df_all['last_name'].str.lower().str.strip()
)

In [15]:
email_base_counts = df_all['email_base'].value_counts()
email_base_counts[email_base_counts > 1]

leo.cox@acornchildcare.com                2
samuel.myers@corelinepackaging.com        2
mason.clark@everwellclinics.com           2
henry.ross@copperlinesecurity.com         2
abigail.morgan@redoakconstruction.com     2
zoey.cole@urbansparkcreative.com          2
riley.peterson@harborlinetransit.com      2
ella.sanders@beaconbiotech.com            2
liam.brooks@nexahealth.io                 2
joseph.hamilton@trailheadoutdoor.co       2
ethan.price@vertexbuildgrp.com            2
nora.hayes@bridgewellfinance.com          2
julian.parker@westfieldtherapy.com        2
victoria.simmons@silverlaketelecom.com    2
sophia.james@bluepeaksoft.com             2
scarlett.long@heliomedia.co               2
david.fisher@peakpointroofing.com         2
olivia.chen@harborfg.com                  2
emma.diaz@pioneerlogistics.com            2
elijah.turner@mapleworksmfg.com           2
amelia.ward@greenlineenergy.com           2
hannah.graham@meridianvet.com             2
noah.reed@stonebridgehr.com               2
matthew.russell@elmstreetfoods.com        2
Name: email_base, dtype: int64

In [16]:
df_all[df_all['email_base'].isin(email_base_counts[email_base_counts > 1].index)] \
    .sort_values(['email_base', 'created_date']) \
    [['lead_id', 'email', 'email_base', 'company', 'lifecycle_stage', 'created_date', 'source_system']]

,lead_id,email,email_base,company,lifecycle_stage,created_date,source_system
44,B-20013,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,RedOak Construction,Lead,2024-07-05,hubspot_B
30,A-10016,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,Red Oak Construction,MQL,2025-06-19,hubspot_A
8,A-10011,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,Greenline Energy,None,2024-04-21,hubspot_A
41,B-20009,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,Green Line Energy,MQL,2024-04-28,hubspot_B
43,B-20024,david.fisher@peakpointroofing.com,david.fisher@peakpointroofing.com,PeakPoint Roofing,MQL,2024-07-02,hubspot_B
14,A-10025,david.fisher@peakpointroofing.com,david.fisher@peakpointroofing.com,PeakPoint Roofing,Opportunity,2024-10-12,hubspot_A
37,B-20004,elijah.turner@mapleworksmfg.com,elijah.turner@mapleworksmfg.com,MapleWorks Manufacturing,SQL,2024-02-21,hubspot_B
7,A-10005,elijah.turner@mapleworksmfg.com,elijah.turner@mapleworksmfg.com,MapleWorks Manufacturing,Opportunity,2024-04-18,hubspot_A
26,A-10017,ella.sanders@beaconbiotech.com,ella.sanders@beaconbiotech.com,Beacon Biotech,None,2025-04-14,hubspot_A
67,B-20016,ella.sanders@beaconbiotech.com,ella.sanders@beaconbiotech.com,Beacon Biotech,SQL,2025-11-02,hubspot_B
4,A-10003,emma.diaz@pioneerlogistics.com,emma.diaz@pioneerlogistics.com,Pioneer Logistics LLC,Opportunity,2024-02-18,hubspot_A
66,B-20002,emma.diaz@pioneerlogistics.com,emma.diaz@pioneerlogistics.com,Pioneer Logistics LLC,SQL,2025-10-30,hubspot_B
53,B-20008,ethan.price@vertexbuildgrp.com,ethan.price@vertexbuildgrp.com,VertexBuild Group,Lead,2025-01-10,hubspot_B
22,A-10010,ethan.price@vertexbuildgrp.com,ethan.price@vertexbuildgrp.com,Vertex Build Group,None,2025-02-20,hubspot_A
3,A-10026,hannah.graham@meridianvet.com,hannah.graham@meridianvet.com,Meridian Veterinary,Lead,2024-02-09,hubspot_A
39,B-20025,hannah.graham@meridianvet.com,hannah.graham@meridianvet.com,Meridian Veterinary,MQL,2024-03-16,hubspot_B
34,A-10015,henry.ross@copperlinesecurity.com,henry.ross@copperlinesecurity.com,Copperline Security,Lead,2025-09-01,hubspot_A
69,B-20012,henry.ross+coadv@copperlinesecurity.com,henry.ross@copperlinesecurity.com,Copper Line Security,Opportunity,2025-11-15,hubspot_B
23,A-10027,joseph.hamilton@trailheadoutdoor.co,joseph.hamilton@trailheadoutdoor.co,Trailhead Outdoor Co,Lead,2025-03-22,hubspot_A
61,B-20026,joseph.hamilton@trailheadoutdoor.co,joseph.hamilton@trailheadoutdoor.co,Trailhead Outdoor Co,Lead,2025-05-13,hubspot_B
47,B-20033,julian.parker@westfieldtherapy.com,julian.parker@westfieldtherapy.com,Westfield Therapy,Lead,2024-08-24,hubspot_B
20,A-10032,julian.parker@westfieldtherapy.com,julian.parker@westfieldtherapy.com,Westfield Therapy,MQL,2025-02-13,hubspot_A
0,A-10031,leo.cox@acornchildcare.com,leo.cox@acornchildcare.com,Acorn Childcare,Lead,2024-01-26,hubspot_A
68,B-20032,leo.cox@acornchildcare.com,leo.cox@acornchildcare.com,Acorn Childcare,Lead,2025-11-05,hubspot_B
1,A-10001,liam.brooks@nexahealth.io,liam.brooks@nexahealth.io,NexaHealth,Opportunity,2024-02-02,hubspot_A
45,B-20000,liam.brooks@nexahealth.io,liam.brooks@nexahealth.io,Nexa Health,Opportunity,2024-07-06,hubspot_B
57,B-20006,mason.clark@everwellclinics.com,mason.clark@everwellclinics.com,Everwell Clinic,SQL,2025-04-14,hubspot_B
35,A-10007,mason.clark@everwellclinics.com,mason.clark@everwellclinics.com,Everwell Clinics,None,2025-11-06,hubspot_A
12,A-10023,matthew.russell@elmstreetfoods.com,matthew.russell@elmstreetfoods.com,Elm Street Foods,Opportunity,2024-08-30,hubspot_A
60,B-20023,matthew.russell@elmstreetfoods.com,matthew.russell@elmstreetfoods.com,Elm Street Foods,SQL,2025-05-13,hubspot_B
36,B-20001,noah.reed@stonebridgehr.com,noah.reed@stonebridgehr.com,Stone Bridge HR,Customer,2024-02-07,hubspot_B
11,A-10002,noah.reed@stonebridgehr.com,noah.reed@stonebridgehr.com,Stonebridge HR,MQL,2024-05-22,hubspot_A
21,A-10029,nora.hayes@bridgewellfinance.com,nora.hayes@bridgewellfinance.com,Bridgewell Finance,SQL,2025-02-19,hubspot_A
63,B-20029,nora.hayes@bridgewellfinance.com,nora.hayes@bridgewellfinance.com,Bridgewell Finance,Customer,2025-06-24,hubspot_B
9,A-10004,olivia.chen@harborfg.com,olivia.chen@harborfg.com,Harbor Financial Grp,SQL,2024-04-27,hubspot_A
56,B-20003,olivia.chen@harborfg.com,olivia.chen@harborfg.com,Harbor Financial Group,MQL,2025-04-07,hubspot_B
27,A-10034,riley.peterson@harborlinetransit.com,riley.peterson@harborlinetransit.com,Harborline Transit,None,2025-05-31,hubspot_A
65,B-20035,riley.peterson@harborlinetransit.com,riley.peterson@harborlinetransit.com,Harborline Transit,MQL,2025-09-21,hubspot_B
38,B-20028,samuel.myers+coadv@corelinepackaging.com,samuel.myers@corelinepackaging.com,Coreline Packaging,Lead,2024-03-01,hubspot_B
15,A-10028,samuel.myers@corelinepackaging.com,samuel.myers@corelinepackaging.com,Coreline Packaging,SQL,2024-11-03,hubspot_A
49,B-20018,scarlett.long@heliomedia.co,scarlett.long@heliomedia.co,Helio Media,Customer,2024-09-22,hubspot_B
24,A-10018,scarlett.long@heliomedia.co,scarlett.long@heliomedia.co,Helio Media,Opportunity,2025-03-24,hubspot_A
51,B-20005,sophia.james@bluepeaksoft.com,sophia.james@bluepeaksoft.com,BluePeak Software,SQL,2024-12-16,hubspot_B
16,A-10006,sophia.james@bluepeaksoft.com,sophia.james@bluepeaksoft.com,Blue Peak Software,Opportunity,2025-01-06,hubspot_A
42,B-20022,victoria.simmons@silverlaketelecom.com,victoria.simmons@silverlaketelecom.com,SilverLake Telecom,MQL,2024-05-06,hubspot_B
17,A-10022,victoria.simmons@silverlaketelecom.com,victoria.simmons@silverlaketelecom.com,SilverLake Telecom,Customer,2025-01-08,hubspot_A
50,B-20031,zoey.cole@urbansparkcreative.com,zoey.cole@urbansparkcreative.com,UrbanSpark Creative,Lead,2024-11-08,hubspot_B
28,A-10030,zoey.cole@urbansparkcreative.com,zoey.cole@urbansparkcreative.com,UrbanSpark Creative,SQL,2025-06-07,hubspot_A

In [17]:
name_company_counts = (
    df_all.groupby(['full_name_clean', 'company_clean'])
    .size()
    .reset_index(name='count')
)

name_company_counts[name_company_counts['count'] > 1]

     full_name_clean             company_clean  count
6      benjamin cook          riverstone legal      2
9       david fisher         peakpoint roofing      2
10     elijah turner  mapleworks manufacturing      2
11      ella sanders            beacon biotech      2
13         emma diaz     pioneer logistics llc      2
17     hannah graham       meridian veterinary      2
18    harper bennett      solstice hospitality      2
23       jack hughes             nova staffing      2
25   joseph hamilton      trailhead outdoor co      2
26     julian parker         westfield therapy      2
28           leo cox           acorn childcare      2
35   matthew russell          elm street foods      2
40        nora hayes        bridgewell finance      2
45    riley peterson        harborline transit      2
46      samuel myers        coreline packaging      2
47     scarlett long               helio media      2
51  victoria simmons        silverlake telecom      2
53         zoey cole       urbanspark creative      2

In [18]:
possible_dupes = name_company_counts[name_company_counts['count'] > 1][['full_name_clean', 'company_clean']]

df_possible_dupes = df_all.merge(possible_dupes, on=['full_name_clean', 'company_clean'], how='inner')

df_possible_dupes.sort_values(['full_name_clean', 'company_clean', 'created_date'])[
    ['lead_id', 'email', 'full_name_clean', 'company', 'company_clean', 'lifecycle_stage', 'created_date', 'source_system']
]

,lead_id,email,full_name_clean,company,company_clean,lifecycle_stage,created_date,source_system
35,B-20011,benjamin.cook@riverstonelegal.com,benjamin cook,Riverstone Legal,riverstone legal,Opportunity,2024-09-09,hubspot_B
34,A-10014,benjamincook@riverstonelegal.com,benjamin cook,Riverstone Legal,riverstone legal,Lead,2025-07-09,hubspot_A
13,B-20024,david.fisher@peakpointroofing.com,david fisher,PeakPoint Roofing,peakpoint roofing,MQL,2024-07-02,hubspot_B
12,A-10025,david.fisher@peakpointroofing.com,david fisher,PeakPoint Roofing,peakpoint roofing,Opportunity,2024-10-12,hubspot_A
9,B-20004,elijah.turner@mapleworksmfg.com,elijah turner,MapleWorks Manufacturing,mapleworks manufacturing,SQL,2024-02-21,hubspot_B
8,A-10005,elijah.turner@mapleworksmfg.com,elijah turner,MapleWorks Manufacturing,mapleworks manufacturing,Opportunity,2024-04-18,hubspot_A
28,A-10017,ella.sanders@beaconbiotech.com,ella sanders,Beacon Biotech,beacon biotech,None,2025-04-14,hubspot_A
29,B-20016,ella.sanders@beaconbiotech.com,ella sanders,Beacon Biotech,beacon biotech,SQL,2025-11-02,hubspot_B
4,A-10003,emma.diaz@pioneerlogistics.com,emma diaz,Pioneer Logistics LLC,pioneer logistics llc,Opportunity,2024-02-18,hubspot_A
5,B-20002,emma.diaz@pioneerlogistics.com,emma diaz,Pioneer Logistics LLC,pioneer logistics llc,SQL,2025-10-30,hubspot_B
2,A-10026,hannah.graham@meridianvet.com,hannah graham,Meridian Veterinary,meridian veterinary,Lead,2024-02-09,hubspot_A
3,B-20025,hannah.graham@meridianvet.com,hannah graham,Meridian Veterinary,meridian veterinary,MQL,2024-03-16,hubspot_B
18,A-10013,harperbennett@solsticehotels.com,harper bennett,Solstice Hospitality,solstice hospitality,None,2025-02-03,hubspot_A
19,B-20010,harper.bennett@solsticehotels.com,harper bennett,Solstice Hospitality,solstice hospitality,SQL,2025-05-30,hubspot_B
6,A-10020,jackhughes@novastaffing.com,jack hughes,Nova Staffing,nova staffing,Lead,2024-02-22,hubspot_A
7,B-20020,jack.hughes@novastaffing.com,jack hughes,Nova Staffing,nova staffing,Lead,2024-12-28,hubspot_B
24,A-10027,joseph.hamilton@trailheadoutdoor.co,joseph hamilton,Trailhead Outdoor Co,trailhead outdoor co,Lead,2025-03-22,hubspot_A
25,B-20026,joseph.hamilton@trailheadoutdoor.co,joseph hamilton,Trailhead Outdoor Co,trailhead outdoor co,Lead,2025-05-13,hubspot_B
21,B-20033,julian.parker@westfieldtherapy.com,julian parker,Westfield Therapy,westfield therapy,Lead,2024-08-24,hubspot_B
20,A-10032,julian.parker@westfieldtherapy.com,julian parker,Westfield Therapy,westfield therapy,MQL,2025-02-13,hubspot_A
0,A-10031,leo.cox@acornchildcare.com,leo cox,Acorn Childcare,acorn childcare,Lead,2024-01-26,hubspot_A
1,B-20032,leo.cox@acornchildcare.com,leo cox,Acorn Childcare,acorn childcare,Lead,2025-11-05,hubspot_B
10,A-10023,matthew.russell@elmstreetfoods.com,matthew russell,Elm Street Foods,elm street foods,Opportunity,2024-08-30,hubspot_A
11,B-20023,matthew.russell@elmstreetfoods.com,matthew russell,Elm Street Foods,elm street foods,SQL,2025-05-13,hubspot_B
22,A-10029,nora.hayes@bridgewellfinance.com,nora hayes,Bridgewell Finance,bridgewell finance,SQL,2025-02-19,hubspot_A
23,B-20029,nora.hayes@bridgewellfinance.com,nora hayes,Bridgewell Finance,bridgewell finance,Customer,2025-06-24,hubspot_B
30,A-10034,riley.peterson@harborlinetransit.com,riley peterson,Harborline Transit,harborline transit,None,2025-05-31,hubspot_A
31,B-20035,riley.peterson@harborlinetransit.com,riley peterson,Harborline Transit,harborline transit,MQL,2025-09-21,hubspot_B
15,B-20028,samuel.myers+coadv@corelinepackaging.com,samuel myers,Coreline Packaging,coreline packaging,Lead,2024-03-01,hubspot_B
14,A-10028,samuel.myers@corelinepackaging.com,samuel myers,Coreline Packaging,coreline packaging,SQL,2024-11-03,hubspot_A
27,B-20018,scarlett.long@heliomedia.co,scarlett long,Helio Media,helio media,Customer,2024-09-22,hubspot_B
26,A-10018,scarlett.long@heliomedia.co,scarlett long,Helio Media,helio media,Opportunity,2025-03-24,hubspot_A
17,B-20022,victoria.simmons@silverlaketelecom.com,victoria simmons,SilverLake Telecom,silverlake telecom,MQL,2024-05-06,hubspot_B
16,A-10022,victoria.simmons@silverlaketelecom.com,victoria simmons,SilverLake Telecom,silverlake telecom,Customer,2025-01-08,hubspot_A
33,B-20031,zoey.cole@urbansparkcreative.com,zoey cole,UrbanSpark Creative,urbanspark creative,Lead,2024-11-08,hubspot_B
32,A-10030,zoey.cole@urbansparkcreative.com,zoey cole,UrbanSpark Creative,urbanspark creative,SQL,2025-06-07,hubspot_A

In [19]:
duplicate_email_base_set = set(email_base_counts[email_base_counts > 1].index)

name_company_dup_keys = set(
    tuple(x) for x in name_company_counts[name_company_counts['count'] > 1][['full_name_clean', 'company_clean']].to_records(index=False)
)

df_all['dup_by_email_base'] = df_all['email_base'].isin(duplicate_email_base_set)

df_all['dup_by_name_company'] = df_all.apply(
    lambda row: (row['full_name_clean'], row['company_clean']) in name_company_dup_keys,
    axis=1
)

df_all['is_possible_duplicate'] = df_all['dup_by_email_base'] | df_all['dup_by_name_company']

In [20]:
df_all['is_possible_duplicate'].value_counts()

True     54
False    18
Name: is_possible_duplicate, dtype: int64

In [21]:
df_all['dedup_key'] = df_all['email_base']

name_company_key = df_all['full_name_clean'] + ' | ' + df_all['company_clean']

df_all.loc[
    (~df_all['dup_by_email_base']) & (df_all['dup_by_name_company']),
    'dedup_key'
] = name_company_key

In [22]:
stage_rank = {
    'Lead': 1,
    'MQL': 2,
    'SQL': 3,
    'Opportunity': 4,
    'Customer': 5
}

df_all['stage_rank'] = df_all['lifecycle_stage'].map(stage_rank)

In [23]:
def first_non_null(series):
    non_null = series.dropna()
    return non_null.iloc[0] if len(non_null) > 0 else pd.NA

def combine_source_systems(series):
    return " | ".join(sorted(series.dropna().astype(str).unique()))

def get_highest_stage(stage_series):
    valid = stage_series.dropna()
    if valid.empty:
        return pd.NA
    return max(valid, key=lambda x: stage_rank.get(x, 0))

In [24]:
master_df = df_all.groupby('dedup_key').agg({
    'lead_id': first_non_null,
    'email_base': first_non_null,
    'email': first_non_null,
    'first_name': first_non_null,
    'last_name': first_non_null,
    'company': first_non_null,
    'job_title': first_non_null,
    'source': first_non_null,
    'created_date': 'min',
    'mql_date': 'min',
    'sql_date': 'min',
    'opportunity_date': 'min',
    'customer_date': 'min',
    'owner': first_non_null,
    'notes': first_non_null,
    'last_updated': first_non_null,
    'source_system': combine_source_systems
}).reset_index()

In [25]:
stage_df = (
    df_all.groupby('dedup_key')['lifecycle_stage']
    .apply(get_highest_stage)
    .reset_index(name='lifecycle_stage_final')
)

master_df = master_df.merge(stage_df, on='dedup_key', how='left')

In [26]:
counts = df_all.groupby('dedup_key').size().reset_index(name='records_merged')

master_df = master_df.merge(counts, on='dedup_key', how='left')

In [27]:
master_df = master_df[
    [
        'dedup_key',
        'lead_id',
        'email_base',
        'email',
        'first_name',
        'last_name',
        'company',
        'job_title',
        'source',
        'lifecycle_stage_final',
        'created_date',
        'mql_date',
        'sql_date',
        'opportunity_date',
        'customer_date',
        'owner',
        'notes',
        'last_updated',
        'source_system',
        'records_merged'
    ]
]

In [28]:
print("Original rows:", len(df_all))
print("Deduplicated rows:", len(master_df))
print()
print(master_df['records_merged'].value_counts())

master_df.head()

Original rows: 72
Deduplicated rows: 45

2    27
1    18
Name: records_merged, dtype: int64

,dedup_key,lead_id,email_base,email,first_name,last_name,company,job_title,source,lifecycle_stage_final,created_date,mql_date,sql_date,opportunity_date,customer_date,owner,notes,last_updated,source_system,records_merged
0,abigail.morgan@redoakconstruction.com,A-10016,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,Abigail,Morgan,Red Oak Construction,HR Manager,Webinar,MQL,2024-07-05,2025-06-27,NaT,NaT,NaT,Jordan Miles,possible duplicate from legacy CRM,2025-06-20,hubspot_A | hubspot_B,2
1,aiden.west@shorelinefoods.com,B-20030,aiden.west@shorelinefoods.com,aiden.west@shorelinefoods.com,Aiden,West,Shoreline Foods,VP Operations,Outbound SDR,Customer,2025-11-16,NaT,2025-12-24,2026-01-22,2026-03-20,Marcus Lee,manually entered,2026-02-25,hubspot_B,1
2,amelia.ward@greenlineenergy.com,A-10011,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,Amelia,Ward,Greenline Energy,HR Director,Direct Traffic,MQL,2024-04-21,2024-04-27,NaT,NaT,NaT,Ben Carter,possible duplicate from legacy CRM,2024-05-03,hubspot_A | hubspot_B,2
3,ava.patel@brightpathco.com,A-10000,ava.patel@brightpathco.com,ava.patel@brightpathco.com,Ava,Patel,Bright Path Consulting,Consultant,Direct Traffic,Lead,2024-09-07,NaT,NaT,NaT,NaT,Jordan Miles,<NA>,2024-10-06,hubspot_A,1
4,benjamin cook | riverstone legal,A-10014,benjamincook@riverstonelegal.com,benjamincook@riverstonelegal.com,Benjamin,Cook,Riverstone Legal,Office Manager,Organic Search,Opportunity,2024-09-09,2024-09-17,2024-10-20,2024-11-27,NaT,Tina Shah,MQL date added later,2025-07-17,hubspot_A | hubspot_B,2

In [29]:
df_all[df_all['is_possible_duplicate']].sort_values(
    ['email_base', 'full_name_clean', 'created_date']
)[
    ['lead_id', 'email', 'email_base', 'full_name_clean', 'company', 'company_clean',
     'lifecycle_stage', 'created_date', 'source_system', 'dup_by_email_base', 'dup_by_name_company']
]

,lead_id,email,email_base,full_name_clean,company,company_clean,lifecycle_stage,created_date,source_system,dup_by_email_base,dup_by_name_company
44,B-20013,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,abigail morgan,RedOak Construction,redoak construction,Lead,2024-07-05,hubspot_B,True,False
30,A-10016,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,abigail morgan,Red Oak Construction,red oak construction,MQL,2025-06-19,hubspot_A,True,False
8,A-10011,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,amelia ward,Greenline Energy,greenline energy,None,2024-04-21,hubspot_A,True,False
41,B-20009,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,amelia ward,Green Line Energy,green line energy,MQL,2024-04-28,hubspot_B,True,False
48,B-20011,benjamin.cook@riverstonelegal.com,benjamin.cook@riverstonelegal.com,benjamin cook,Riverstone Legal,riverstone legal,Opportunity,2024-09-09,hubspot_B,False,True
31,A-10014,benjamincook@riverstonelegal.com,benjamincook@riverstonelegal.com,benjamin cook,Riverstone Legal,riverstone legal,Lead,2025-07-09,hubspot_A,False,True
43,B-20024,david.fisher@peakpointroofing.com,david.fisher@peakpointroofing.com,david fisher,PeakPoint Roofing,peakpoint roofing,MQL,2024-07-02,hubspot_B,True,True
14,A-10025,david.fisher@peakpointroofing.com,david.fisher@peakpointroofing.com,david fisher,PeakPoint Roofing,peakpoint roofing,Opportunity,2024-10-12,hubspot_A,True,True
37,B-20004,elijah.turner@mapleworksmfg.com,elijah.turner@mapleworksmfg.com,elijah turner,MapleWorks Manufacturing,mapleworks manufacturing,SQL,2024-02-21,hubspot_B,True,True
7,A-10005,elijah.turner@mapleworksmfg.com,elijah.turner@mapleworksmfg.com,elijah turner,MapleWorks Manufacturing,mapleworks manufacturing,Opportunity,2024-04-18,hubspot_A,True,True
26,A-10017,ella.sanders@beaconbiotech.com,ella.sanders@beaconbiotech.com,ella sanders,Beacon Biotech,beacon biotech,None,2025-04-14,hubspot_A,True,True
67,B-20016,ella.sanders@beaconbiotech.com,ella.sanders@beaconbiotech.com,ella sanders,Beacon Biotech,beacon biotech,SQL,2025-11-02,hubspot_B,True,True
4,A-10003,emma.diaz@pioneerlogistics.com,emma.diaz@pioneerlogistics.com,emma diaz,Pioneer Logistics LLC,pioneer logistics llc,Opportunity,2024-02-18,hubspot_A,True,True
66,B-20002,emma.diaz@pioneerlogistics.com,emma.diaz@pioneerlogistics.com,emma diaz,Pioneer Logistics LLC,pioneer logistics llc,SQL,2025-10-30,hubspot_B,True,True
53,B-20008,ethan.price@vertexbuildgrp.com,ethan.price@vertexbuildgrp.com,ethan price,VertexBuild Group,vertexbuild group,Lead,2025-01-10,hubspot_B,True,False
22,A-10010,ethan.price@vertexbuildgrp.com,ethan.price@vertexbuildgrp.com,ethan price,Vertex Build Group,vertex build group,None,2025-02-20,hubspot_A,True,False
3,A-10026,hannah.graham@meridianvet.com,hannah.graham@meridianvet.com,hannah graham,Meridian Veterinary,meridian veterinary,Lead,2024-02-09,hubspot_A,True,True
39,B-20025,hannah.graham@meridianvet.com,hannah.graham@meridianvet.com,hannah graham,Meridian Veterinary,meridian veterinary,MQL,2024-03-16,hubspot_B,True,True
62,B-20010,harper.bennett@solsticehotels.com,harper.bennett@solsticehotels.com,harper bennett,Solstice Hospitality,solstice hospitality,SQL,2025-05-30,hubspot_B,False,True
19,A-10013,harperbennett@solsticehotels.com,harperbennett@solsticehotels.com,harper bennett,Solstice Hospitality,solstice hospitality,None,2025-02-03,hubspot_A,False,True
34,A-10015,henry.ross@copperlinesecurity.com,henry.ross@copperlinesecurity.com,henry ross,Copperline Security,copperline security,Lead,2025-09-01,hubspot_A,True,False
69,B-20012,henry.ross+coadv@copperlinesecurity.com,henry.ross@copperlinesecurity.com,henry ross,Copper Line Security,copper line security,Opportunity,2025-11-15,hubspot_B,True,False
52,B-20020,jack.hughes@novastaffing.com,jack.hughes@novastaffing.com,jack hughes,Nova Staffing,nova staffing,Lead,2024-12-28,hubspot_B,False,True
6,A-10020,jackhughes@novastaffing.com,jackhughes@novastaffing.com,jack hughes,Nova Staffing,nova staffing,Lead,2024-02-22,hubspot_A,False,True
23,A-10027,joseph.hamilton@trailheadoutdoor.co,joseph.hamilton@trailheadoutdoor.co,joseph hamilton,Trailhead Outdoor Co,trailhead outdoor co,Lead,2025-03-22,hubspot_A,True,True
61,B-20026,joseph.hamilton@trailheadoutdoor.co,joseph.hamilton@trailheadoutdoor.co,joseph hamilton,Trailhead Outdoor Co,trailhead outdoor co,Lead,2025-05-13,hubspot_B,True,True
47,B-20033,julian.parker@westfieldtherapy.com,julian.parker@westfieldtherapy.com,julian parker,Westfield Therapy,westfield therapy,Lead,2024-08-24,hubspot_B,True,True
20,A-10032,julian.parker@westfieldtherapy.com,julian.parker@westfieldtherapy.com,julian parker,Westfield Therapy,westfield therapy,MQL,2025-02-13,hubspot_A,True,True
0,A-10031,leo.cox@acornchildcare.com,leo.cox@acornchildcare.com,leo cox,Acorn Childcare,acorn childcare,Lead,2024-01-26,hubspot_A,True,True
68,B-20032,leo.cox@acornchildcare.com,leo.cox@acornchildcare.com,leo cox,Acorn Childcare,acorn childcare,Lead,2025-11-05,hubspot_B,True,True
1,A-10001,liam.brooks@nexahealth.io,liam.brooks@nexahealth.io,liam brooks,NexaHealth,nexahealth,Opportunity,2024-02-02,hubspot_A,True,False
45,B-20000,liam.brooks@nexahealth.io,liam.brooks@nexahealth.io,liam brooks,Nexa Health,nexa health,Opportunity,2024-07-06,hubspot_B,True,False
57,B-20006,mason.clark@everwellclinics.com,mason.clark@everwellclinics.com,mason clark,Everwell Clinic,everwell clinic,SQL,2025-04-14,hubspot_B,True,False
35,A-10007,mason.clark@everwellclinics.com,mason.clark@everwellclinics.com,mason clark,Everwell Clinics,everwell clinics,None,2025-11-06,hubspot_A,True,False
12,A-10023,matthew.russell@elmstreetfoods.com,matthew.russell@elmstreetfoods.com,matthew russell,Elm Street Foods,elm street foods,Opportunity,2024-08-30,hubspot_A,True,True
60,B-20023,matthew.russell@elmstreetfoods.com,matthew.russell@elmstreetfoods.com,matthew russell,Elm Street Foods,elm street foods,SQL,2025-05-13,hubspot_B,True,True
36,B-20001,noah.reed@stonebridgehr.com,noah.reed@stonebridgehr.com,noah reed,Stone Bridge HR,stone bridge hr,Customer,2024-02-07,hubspot_B,True,False
11,A-10002,noah.reed@stonebridgehr.com,noah.reed@stonebridgehr.com,noah reed,Stonebridge HR,stonebridge hr,MQL,2024-05-22,hubspot_A,True,False
21,A-10029,nora.hayes@bridgewellfinance.com,nora.hayes@bridgewellfinance.com,nora hayes,Bridgewell Finance,bridgewell finance,SQL,2025-02-19,hubspot_A,True,True
63,B-20029,nora.hayes@bridgewellfinance.com,nora.hayes@bridgewellfinance.com,nora hayes,Bridgewell Finance,bridgewell finance,Customer,2025-06-24,hubspot_B,True,True
9,A-10004,olivia.chen@harborfg.com,olivia.chen@harborfg.com,olivia chen,Harbor Financial Grp,harbor financial grp,SQL,2024-04-27,hubspot_A,True,False
56,B-20003,olivia.chen@harborfg.com,olivia.chen@harborfg.com,olivia chen,Harbor Financial Group,harbor financial group,MQL,2025-04-07,hubspot_B,True,False
27,A-10034,riley.peterson@harborlinetransit.com,riley.peterson@harborlinetransit.com,riley peterson,Harborline Transit,harborline transit,None,2025-05-31,hubspot_A,True,True
65,B-20035,riley.peterson@harborlinetransit.com,riley.peterson@harborlinetransit.com,riley peterson,Harborline Transit,harborline transit,MQL,2025-09-21,hubspot_B,True,True
38,B-20028,samuel.myers+coadv@corelinepackaging.com,samuel.myers@corelinepackaging.com,samuel myers,Coreline Packaging,coreline packaging,Lead,2024-03-01,hubspot_B,True,True
15,A-10028,samuel.myers@corelinepackaging.com,samuel.myers@corelinepackaging.com,samuel myers,Coreline Packaging,coreline packaging,SQL,2024-11-03,hubspot_A,True,True
49,B-20018,scarlett.long@heliomedia.co,scarlett.long@heliomedia.co,scarlett long,Helio Media,helio media,Customer,2024-09-22,hubspot_B,True,True
24,A-10018,scarlett.long@heliomedia.co,scarlett.long@heliomedia.co,scarlett long,Helio Media,helio media,Opportunity,2025-03-24,hubspot_A,True,True
51,B-20005,sophia.james@bluepeaksoft.com,sophia.james@bluepeaksoft.com,sophia james,BluePeak Software,bluepeak software,SQL,2024-12-16,hubspot_B,True,False
16,A-10006,sophia.james@bluepeaksoft.com,sophia.james@bluepeaksoft.com,sophia james,Blue Peak Software,blue peak software,Opportunity,2025-01-06,hubspot_A,True,False
42,B-20022,victoria.simmons@silverlaketelecom.com,victoria.simmons@silverlaketelecom.com,victoria simmons,SilverLake Telecom,silverlake telecom,MQL,2024-05-06,hubspot_B,True,True
17,A-10022,victoria.simmons@silverlaketelecom.com,victoria.simmons@silverlaketelecom.com,victoria simmons,SilverLake Telecom,silverlake telecom,Customer,2025-01-08,hubspot_A,True,True
50,B-20031,zoey.cole@urbansparkcreative.com,zoey.cole@urbansparkcreative.com,zoey cole,UrbanSpark Creative,urbanspark creative,Lead,2024-11-08,hubspot_B,True,True
28,A-10030,zoey.cole@urbansparkcreative.com,zoey.cole@urbansparkcreative.com,zoey cole,UrbanSpark Creative,urbanspark creative,SQL,2025-06-07,hubspot_A,True,True

## Deduplication Strategy

To create a unified lead record across merged HubSpot instances:

1. Identify duplicates using:
   - Normalized email (email_base)
   - Name + company combination
   
  
2. For each duplicate group:
   - Keep earliest created_date (first touch)
   - Keep latest lifecycle_stage (most advanced stage)
   - Combine stage dates by taking non-null values
   - Prefer non-null values across fields (coalesce logic)

3. Treat each group as one unique lead

In [30]:
# Start with normalized email as default group key
df_all['dedup_key'] = df_all['email_base']

# For records not caught well by email pattern differences,
# use name + company as fallback grouping signal
name_company_key = df_all['full_name_clean'] + ' | ' + df_all['company_clean']

# If a record is duplicate by name/company but not by email_base,
# use the name-company key
df_all.loc[
    (~df_all['dup_by_email_base']) & (df_all['dup_by_name_company']),
    'dedup_key'
] = name_company_key

In [31]:
stage_rank = {
    'Lead': 1,
    'MQL': 2,
    'SQL': 3,
    'Opportunity': 4,
    'Customer': 5
}

df_all['stage_rank'] = df_all['lifecycle_stage'].map(stage_rank)

In [32]:
def get_max_stage(series):
    valid_stages = series.dropna()
    if valid_stages.empty:
        return pd.NA
    
    return valid_stages.map(stage_rank).idxmax()

In [33]:
def get_highest_stage(stage_series):
    valid_stages = stage_series.dropna()
    if valid_stages.empty:
        return pd.NA
    
    highest_stage = max(valid_stages, key=lambda x: stage_rank.get(x, 0))
    return highest_stage

In [34]:
def first_non_null(series):
    non_null = series.dropna()
    return non_null.iloc[0] if len(non_null) > 0 else pd.NA

def combine_source_systems(series):
    return " | ".join(sorted(series.dropna().astype(str).unique()))

master_df = df_all.groupby('dedup_key').agg({
    'lead_id': first_non_null,
    'email_base': first_non_null,
    'email': first_non_null,
    'first_name': first_non_null,
    'last_name': first_non_null,
    'company': first_non_null,
    'job_title': first_non_null,
    'source': first_non_null,
    'created_date': 'min',
    'mql_date': 'min',
    'sql_date': 'min',
    'opportunity_date': 'min',
    'customer_date': 'min',
    'owner': first_non_null,
    'notes': first_non_null,
    'last_updated': first_non_null,
    'source_system': combine_source_systems
}).reset_index()

In [35]:
highest_stage_df = (
    df_all.groupby('dedup_key')['lifecycle_stage']
    .apply(get_highest_stage)
    .reset_index(name='lifecycle_stage_final')
)

master_df = master_df.merge(highest_stage_df, on='dedup_key', how='left')

In [36]:
group_sizes = (
    df_all.groupby('dedup_key')
    .size()
    .reset_index(name='records_merged')
)

master_df = master_df.merge(group_sizes, on='dedup_key', how='left')

In [37]:
master_df = master_df[
    [
        'dedup_key',
        'lead_id',
        'email_base',
        'email',
        'first_name',
        'last_name',
        'company',
        'job_title',
        'source',
        'lifecycle_stage_final',
        'created_date',
        'mql_date',
        'sql_date',
        'opportunity_date',
        'customer_date',
        'owner',
        'notes',
        'last_updated',
        'source_system',
        'records_merged'
    ]
]

In [38]:
print("Original combined rows:", len(df_all))
print("Master deduplicated rows:", len(master_df))

master_df.head()

Original combined rows: 72
Master deduplicated rows: 45

,dedup_key,lead_id,email_base,email,first_name,last_name,company,job_title,source,lifecycle_stage_final,created_date,mql_date,sql_date,opportunity_date,customer_date,owner,notes,last_updated,source_system,records_merged
0,abigail.morgan@redoakconstruction.com,A-10016,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,Abigail,Morgan,Red Oak Construction,HR Manager,Webinar,MQL,2024-07-05,2025-06-27,NaT,NaT,NaT,Jordan Miles,possible duplicate from legacy CRM,2025-06-20,hubspot_A | hubspot_B,2
1,aiden.west@shorelinefoods.com,B-20030,aiden.west@shorelinefoods.com,aiden.west@shorelinefoods.com,Aiden,West,Shoreline Foods,VP Operations,Outbound SDR,Customer,2025-11-16,NaT,2025-12-24,2026-01-22,2026-03-20,Marcus Lee,manually entered,2026-02-25,hubspot_B,1
2,amelia.ward@greenlineenergy.com,A-10011,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,Amelia,Ward,Greenline Energy,HR Director,Direct Traffic,MQL,2024-04-21,2024-04-27,NaT,NaT,NaT,Ben Carter,possible duplicate from legacy CRM,2024-05-03,hubspot_A | hubspot_B,2
3,ava.patel@brightpathco.com,A-10000,ava.patel@brightpathco.com,ava.patel@brightpathco.com,Ava,Patel,Bright Path Consulting,Consultant,Direct Traffic,Lead,2024-09-07,NaT,NaT,NaT,NaT,Jordan Miles,<NA>,2024-10-06,hubspot_A,1
4,benjamin cook | riverstone legal,A-10014,benjamincook@riverstonelegal.com,benjamincook@riverstonelegal.com,Benjamin,Cook,Riverstone Legal,Office Manager,Organic Search,Opportunity,2024-09-09,2024-09-17,2024-10-20,2024-11-27,NaT,Tina Shah,MQL date added later,2025-07-17,hubspot_A | hubspot_B,2

In [39]:
master_df[master_df['records_merged'] > 1].sort_values(
    ['records_merged', 'created_date'],
    ascending=[False, True]
)

,dedup_key,lead_id,email_base,email,first_name,last_name,company,job_title,source,lifecycle_stage_final,created_date,mql_date,sql_date,opportunity_date,customer_date,owner,notes,last_updated,source_system,records_merged
24,leo.cox@acornchildcare.com,A-10031,leo.cox@acornchildcare.com,leo.cox@acornchildcare.com,Leo,Cox,Acorn Childcare,Founder,Trade Show,Lead,2024-01-26,NaT,NaT,NaT,NaT,Priya Nair,owner changed after routing,2024-03-29,hubspot_A | hubspot_B,2
26,liam.brooks@nexahealth.io,A-10001,liam.brooks@nexahealth.io,liam.brooks@nexahealth.io,Liam,Brooks,NexaHealth,Operations Manager,Referral,Opportunity,2024-02-02,2024-02-14,2024-03-02,2024-03-06,NaT,Tina Shah,owner changed after routing,2024-03-06,hubspot_A | hubspot_B,2
32,noah.reed@stonebridgehr.com,A-10002,noah.reed@stonebridgehr.com,noah.reed@stonebridgehr.com,Noah,Reed,Stonebridge HR,HR Director,Partner,Customer,2024-02-07,2024-02-16,2024-02-13,2024-04-06,2024-05-13,Priya Nair,Jordan updated stage after call,2024-06-02,hubspot_A | hubspot_B,2
14,hannah.graham@meridianvet.com,A-10026,hannah.graham@meridianvet.com,hannah.graham@meridianvet.com,Hannah,Graham,Meridian Veterinary,Practice Manager,Paid Search,MQL,2024-02-09,2024-03-31,NaT,NaT,NaT,Marcus Lee,MQL date added later,2024-02-14,hubspot_A | hubspot_B,2
11,emma.diaz@pioneerlogistics.com,A-10003,emma.diaz@pioneerlogistics.com,emma.diaz@pioneerlogistics.com,Emma,Diaz,Pioneer Logistics LLC,VP People,Direct Traffic,Opportunity,2024-02-18,2025-11-11,2024-03-03,2024-04-15,NaT,Jordan Miles,MQL date added later,2024-05-15,hubspot_A | hubspot_B,2
8,elijah.turner@mapleworksmfg.com,A-10005,elijah.turner@mapleworksmfg.com,elijah.turner@mapleworksmfg.com,Elijah,Turner,MapleWorks Manufacturing,People Ops Manager,Organic Search,Opportunity,2024-02-21,2024-02-28,2024-03-07,2024-07-06,NaT,Jordan Miles,possible duplicate from legacy CRM,2024-08-14,hubspot_A | hubspot_B,2
19,jack hughes | nova staffing,A-10020,jackhughes@novastaffing.com,jackhughes@novastaffing.com,Jack,Hughes,Nova Staffing,Sales Director,Partner,Lead,2024-02-22,NaT,NaT,NaT,NaT,Sofia Gomez,possible duplicate from legacy CRM,2024-04-16,hubspot_A | hubspot_B,2
38,samuel.myers@corelinepackaging.com,A-10028,samuel.myers@corelinepackaging.com,samuel.myers@corelinepackaging.com,Samuel,Myers,Coreline Packaging,Finance Director,Partner,SQL,2024-03-01,2024-11-24,2024-12-20,NaT,NaT,Ben Carter,Jordan updated stage after call,2024-12-11,hubspot_A | hubspot_B,2
2,amelia.ward@greenlineenergy.com,A-10011,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,Amelia,Ward,Greenline Energy,HR Director,Direct Traffic,MQL,2024-04-21,2024-04-27,NaT,NaT,NaT,Ben Carter,possible duplicate from legacy CRM,2024-05-03,hubspot_A | hubspot_B,2
34,olivia.chen@harborfg.com,A-10004,olivia.chen@harborfg.com,olivia.chen@harborfg.com,Olivia,Chen,Harbor Financial Grp,Recruiting Lead,Direct Traffic,SQL,2024-04-27,2024-05-14,2024-05-31,NaT,NaT,Tina Shah,MQL date added later,2024-06-30,hubspot_A | hubspot_B,2
42,victoria.simmons@silverlaketelecom.com,A-10022,victoria.simmons@silverlaketelecom.com,victoria.simmons@silverlaketelecom.com,Victoria,Simmons,SilverLake Telecom,Comp & Benefits Manager,Trade Show,Customer,2024-05-06,2024-05-09,2025-02-04,2025-02-26,2025-03-14,Tina Shah,MQL date added later,2025-05-06,hubspot_A | hubspot_B,2
7,david.fisher@peakpointroofing.com,A-10025,david.fisher@peakpointroofing.com,david.fisher@peakpointroofing.com,David,Fisher,PeakPoint Roofing,Operations Director,Paid Search,Opportunity,2024-07-02,2024-07-17,2024-11-22,2024-12-14,NaT,Ben Carter,imported from webinar list,2024-11-14,hubspot_A | hubspot_B,2
0,abigail.morgan@redoakconstruction.com,A-10016,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,Abigail,Morgan,Red Oak Construction,HR Manager,Webinar,MQL,2024-07-05,2025-06-27,NaT,NaT,NaT,Jordan Miles,possible duplicate from legacy CRM,2025-06-20,hubspot_A | hubspot_B,2
22,julian.parker@westfieldtherapy.com,A-10032,julian.parker@westfieldtherapy.com,julian.parker@westfieldtherapy.com,Julian,Parker,Westfield Therapy,Clinic Administrator,Partner,MQL,2024-08-24,2025-03-05,NaT,NaT,NaT,Tina Shah,entered manually by marketing,2025-06-10,hubspot_A | hubspot_B,2
29,matthew.russell@elmstreetfoods.com,A-10023,matthew.russell@elmstreetfoods.com,matthew.russell@elmstreetfoods.com,Matthew,Russell,Elm Street Foods,HR Manager,Paid Search,Opportunity,2024-08-30,2024-09-24,2024-10-05,2024-10-31,NaT,Sofia Gomez,imported from webinar list,2024-09-12,hubspot_A | hubspot_B,2
4,benjamin cook | riverstone legal,A-10014,benjamincook@riverstonelegal.com,benjamincook@riverstonelegal.com,Benjamin,Cook,Riverstone Legal,Office Manager,Organic Search,Opportunity,2024-09-09,2024-09-17,2024-10-20,2024-11-27,NaT,Tina Shah,MQL date added later,2025-07-17,hubspot_A | hubspot_B,2
39,scarlett.long@heliomedia.co,A-10018,scarlett.long@heliomedia.co,scarlett.long@heliomedia.co,Scarlett,Long,Helio Media,Revenue Operations Manager,Organic Search,Customer,2024-09-22,2024-10-10,2024-10-11,2024-11-23,2025-01-17,Jordan Miles,imported from webinar list,2025-06-27,hubspot_A | hubspot_B,2
44,zoey.cole@urbansparkcreative.com,A-10030,zoey.cole@urbansparkcreative.com,zoey.cole@urbansparkcreative.com,Zoey,Cole,UrbanSpark Creative,Office Manager,Direct Traffic,SQL,2024-11-08,2025-07-02,2025-07-12,NaT,NaT,Tina Shah,Jordan updated stage after call,2025-06-25,hubspot_A | hubspot_B,2
41,sophia.james@bluepeaksoft.com,A-10006,sophia.james@bluepeaksoft.com,sophia.james@bluepeaksoft.com,Sophia,James,Blue Peak Software,HRBP,Partner,Opportunity,2024-12-16,2024-12-28,2025-01-22,2025-03-06,NaT,Tina Shah,duplicate suspected,2025-01-22,hubspot_A | hubspot_B,2
12,ethan.price@vertexbuildgrp.com,A-10010,ethan.price@vertexbuildgrp.com,ethan.price@vertexbuildgrp.com,Ethan,Price,Vertex Build Group,Talent Manager,Referral,Lead,2025-01-10,2025-02-23,NaT,NaT,NaT,Sofia Gomez,entered manually by marketing,2025-04-04,hubspot_A | hubspot_B,2
15,harper bennett | solstice hospitality,A-10013,harperbennett@solsticehotels.com,harperbennett@solsticehotels.com,Harper,Bennett,Solstice Hospitality,Regional HR Manager,Paid Search,SQL,2025-02-03,2025-02-28,2025-07-07,NaT,NaT,Jordan Miles,imported from webinar list,2025-04-18,hubspot_A | hubspot_B,2
33,nora.hayes@bridgewellfinance.com,A-10029,nora.hayes@bridgewellfinance.com,nora.hayes@bridgewellfinance.com,Nora,Hayes,Bridgewell Finance,HR Director,Referral,Customer,2025-02-19,2025-02-19,2025-03-10,2025-08-10,2025-09-22,Sofia Gomez,possible duplicate from legacy CRM,2025-03-18,hubspot_A | hubspot_B,2
21,joseph.hamilton@trailheadoutdoor.co,A-10027,joseph.hamilton@trailheadoutdoor.co,joseph.hamilton@trailheadoutdoor.co,Joseph,Hamilton,Trailhead Outdoor Co,People Director,Direct Traffic,Lead,2025-03-22,NaT,NaT,NaT,NaT,Jordan Miles,owner changed after routing,2025-06-22,hubspot_A | hubspot_B,2
9,ella.sanders@beaconbiotech.com,A-10017,ella.sanders@beaconbiotech.com,ella.sanders@beaconbiotech.com,Ella,Sanders,Beacon Biotech,HR Lead,Webinar,SQL,2025-04-14,2025-05-02,2025-05-08,NaT,NaT,Marcus Lee,Jordan updated stage after call,2025-05-04,hubspot_A | hubspot_B,2
28,mason.clark@everwellclinics.com,A-10007,mason.clark@everwellclinics.com,mason.clark@everwellclinics.com,Mason,Clark,Everwell Clinics,Controller,Trade Show,SQL,2025-04-14,2025-11-23,2025-05-18,NaT,NaT,Sofia Gomez,possible duplicate from legacy CRM,2025-12-23,hubspot_A | hubspot_B,2
37,riley.peterson@harborlinetransit.com,A-10034,riley.peterson@harborlinetransit.com,riley.peterson@harborlinetransit.com,Riley,Peterson,Harborline Transit,Safety Director,Trade Show,MQL,2025-05-31,2025-06-17,NaT,NaT,NaT,Marcus Lee,stage synced late,2025-09-06,hubspot_A | hubspot_B,2
16,henry.ross@copperlinesecurity.com,A-10015,henry.ross@copperlinesecurity.com,henry.ross@copperlinesecurity.com,Henry,Ross,Copperline Security,COO,Trade Show,Opportunity,2025-09-01,2025-11-30,2025-12-06,2025-12-06,NaT,Ben Carter,possible duplicate from legacy CRM,2025-11-12,hubspot_A | hubspot_B,2

In [40]:
sample_key = master_df.loc[master_df['records_merged'] > 1, 'dedup_key'].iloc[0]
df_all[df_all['dedup_key'] == sample_key].sort_values('created_date')

,lead_id,email,first_name,last_name,company,job_title,source,lifecycle_stage,created_date,mql_date,...,last_updated,source_system,email_base,company_clean,full_name_clean,dup_by_email_base,dup_by_name_company,is_possible_duplicate,dedup_key,stage_rank
44,B-20013,abigail.morgan@redoakconstruction.com,Abigail,Morgan,RedOak Construction,HR Manager,Direct,Lead,2024-07-05,NaT,...,2024-10-28,hubspot_B,abigail.morgan@redoakconstruction.com,redoak construction,abigail morgan,True,False,True,abigail.morgan@redoakconstruction.com,1.0
30,A-10016,abigail.morgan@redoakconstruction.com,Abigail,Morgan,Red Oak Construction,HR Manager,Webinar,MQL,2025-06-19,2025-06-27,...,2025-06-20,hubspot_A,abigail.morgan@redoakconstruction.com,red oak construction,abigail morgan,True,False,True,abigail.morgan@redoakconstruction.com,2.0

In [41]:
df_all.to_csv("../data/interim/combined_with_dedup_flags.csv", index=False)

In [42]:
master_df.to_csv("../data/processed/master_deduplicated_leads.csv", index=False)

In [43]:
print("Saved combined dataset to ../data/interim/combined_with_dedup_flags.csv")
print("Saved master dataset to ../data/processed/master_deduplicated_leads.csv")

Saved combined dataset to ../data/interim/combined_with_dedup_flags.csv
Saved master dataset to ../data/processed/master_deduplicated_leads.csv

In [44]:
master_df

,dedup_key,lead_id,email_base,email,first_name,last_name,company,job_title,source,lifecycle_stage_final,created_date,mql_date,sql_date,opportunity_date,customer_date,owner,notes,last_updated,source_system,records_merged
0,abigail.morgan@redoakconstruction.com,A-10016,abigail.morgan@redoakconstruction.com,abigail.morgan@redoakconstruction.com,Abigail,Morgan,Red Oak Construction,HR Manager,Webinar,MQL,2024-07-05,2025-06-27,NaT,NaT,NaT,Jordan Miles,possible duplicate from legacy CRM,2025-06-20,hubspot_A | hubspot_B,2
1,aiden.west@shorelinefoods.com,B-20030,aiden.west@shorelinefoods.com,aiden.west@shorelinefoods.com,Aiden,West,Shoreline Foods,VP Operations,Outbound SDR,Customer,2025-11-16,NaT,2025-12-24,2026-01-22,2026-03-20,Marcus Lee,manually entered,2026-02-25,hubspot_B,1
2,amelia.ward@greenlineenergy.com,A-10011,amelia.ward@greenlineenergy.com,amelia.ward@greenlineenergy.com,Amelia,Ward,Greenline Energy,HR Director,Direct Traffic,MQL,2024-04-21,2024-04-27,NaT,NaT,NaT,Ben Carter,possible duplicate from legacy CRM,2024-05-03,hubspot_A | hubspot_B,2
3,ava.patel@brightpathco.com,A-10000,ava.patel@brightpathco.com,ava.patel@brightpathco.com,Ava,Patel,Bright Path Consulting,Consultant,Direct Traffic,Lead,2024-09-07,NaT,NaT,NaT,NaT,Jordan Miles,<NA>,2024-10-06,hubspot_A,1
4,benjamin cook | riverstone legal,A-10014,benjamincook@riverstonelegal.com,benjamincook@riverstonelegal.com,Benjamin,Cook,Riverstone Legal,Office Manager,Organic Search,Opportunity,2024-09-09,2024-09-17,2024-10-20,2024-11-27,NaT,Tina Shah,MQL date added later,2025-07-17,hubspot_A | hubspot_B,2
5,chloe.foster@truenorthlabs.ai,A-10021,chloe.foster@truenorthlabs.ai,chloe.foster@truenorthlabs.ai,Chloe,Foster,TrueNorth Labs,People Ops Specialist,Paid Search,Lead,2025-07-28,NaT,NaT,NaT,NaT,Jordan Miles,possible duplicate from legacy CRM,2025-09-05,hubspot_A,1
6,daniel.bryant@orbitfreight.com,B-20015,daniel.bryant@orbitfreight.com,daniel.bryant@orbitfreight.com,Daniel,Bryant,Orbit Freight,Director HRIS,organic,Lead,2024-07-10,NaT,NaT,NaT,NaT,Sofia Gomez,marketing updated after event,2024-09-15,hubspot_B,1
7,david.fisher@peakpointroofing.com,A-10025,david.fisher@peakpointroofing.com,david.fisher@peakpointroofing.com,David,Fisher,PeakPoint Roofing,Operations Director,Paid Search,Opportunity,2024-07-02,2024-07-17,2024-11-22,2024-12-14,NaT,Ben Carter,imported from webinar list,2024-11-14,hubspot_A | hubspot_B,2
8,elijah.turner@mapleworksmfg.com,A-10005,elijah.turner@mapleworksmfg.com,elijah.turner@mapleworksmfg.com,Elijah,Turner,MapleWorks Manufacturing,People Ops Manager,Organic Search,Opportunity,2024-02-21,2024-02-28,2024-03-07,2024-07-06,NaT,Jordan Miles,possible duplicate from legacy CRM,2024-08-14,hubspot_A | hubspot_B,2
9,ella.sanders@beaconbiotech.com,A-10017,ella.sanders@beaconbiotech.com,ella.sanders@beaconbiotech.com,Ella,Sanders,Beacon Biotech,HR Lead,Webinar,SQL,2025-04-14,2025-05-02,2025-05-08,NaT,NaT,Marcus Lee,Jordan updated stage after call,2025-05-04,hubspot_A | hubspot_B,2
10,emily.watson@firstharborbank.com,B-20014,emily.watson@firstharborbank.com,emily.watson@firstharborbank.com,Emily,Watson,First Harbor Bank,SVP Talent,Paid Social,MQL,2025-04-29,2025-05-17,NaT,NaT,NaT,Tina Shah,marketing updated after event,2025-05-18,hubspot_B,1
11,emma.diaz@pioneerlogistics.com,A-10003,emma.diaz@pioneerlogistics.com,emma.diaz@pioneerlogistics.com,Emma,Diaz,Pioneer Logistics LLC,VP People,Direct Traffic,Opportunity,2024-02-18,2025-11-11,2024-03-03,2024-04-15,NaT,Jordan Miles,MQL date added later,2024-05-15,hubspot_A | hubspot_B,2
12,ethan.price@vertexbuildgrp.com,A-10010,ethan.price@vertexbuildgrp.com,ethan.price@vertexbuildgrp.com,Ethan,Price,Vertex Build Group,Talent Manager,Referral,Lead,2025-01-10,2025-02-23,NaT,NaT,NaT,Sofia Gomez,entered manually by marketing,2025-04-04,hubspot_A | hubspot_B,2
13,grace.perry@primestonerealty.com,A-10019,grace.perry@primestonerealty.com,grace.perry@primestonerealty.com,Grace,Perry,PrimeStone Realty,COO,Referral,Lead,2025-07-20,NaT,NaT,NaT,NaT,Marcus Lee,MQL date added later,2025-11-12,hubspot_A,1
14,hannah.graham@meridianvet.com,A-10026,hannah.graham@meridianvet.com,hannah.graham@meridianvet.com,Hannah,Graham,Meridian Veterinary,Practice Manager,Paid Search,MQL,2024-02-09,2024-03-31,NaT,NaT,NaT,Marcus Lee,MQL date added later,2024-02-14,hubspot_A | hubspot_B,2
15,harper bennett | solstice hospitality,A-10013,harperbennett@solsticehotels.com,harperbennett@solsticehotels.com,Harper,Bennett,Solstice Hospitality,Regional HR Manager,Paid Search,SQL,2025-02-03,2025-02-28,2025-07-07,NaT,NaT,Jordan Miles,imported from webinar list,2025-04-18,hubspot_A | hubspot_B,2
16,henry.ross@copperlinesecurity.com,A-10015,henry.ross@copperlinesecurity.com,henry.ross@copperlinesecurity.com,Henry,Ross,Copperline Security,COO,Trade Show,Opportunity,2025-09-01,2025-11-30,2025-12-06,2025-12-06,NaT,Ben Carter,possible duplicate from legacy CRM,2025-11-12,hubspot_A | hubspot_B,2
17,isabella.kelly@summitretailpartners.com,B-20007,isabella.kelly@summitretailpartners.com,isabella.kelly@summitretailpartners.com,Isabella,Kelly,Summit Retail,VP HR,Paid Social,MQL,2025-11-28,2025-12-23,NaT,NaT,NaT,Priya Nair,<NA>,2026-03-05,hubspot_B,1
18,isabellakelly@summitretailpartners.com,A-10008,isabellakelly@summitretailpartners.com,isabellakelly@summitretailpartners.com,Isabella,Kelly,Summit Retail Partners,VP HR,Organic Search,Customer,2025-03-24,NaT,2025-04-14,2025-04-29,2025-05-16,Tina Shah,owner changed after routing,2025-04-01,hubspot_A,1
19,jack hughes | nova staffing,A-10020,jackhughes@novastaffing.com,jackhughes@novastaffing.com,Jack,Hughes,Nova Staffing,Sales Director,Partner,Lead,2024-02-22,NaT,NaT,NaT,NaT,Sofia Gomez,possible duplicate from legacy CRM,2024-04-16,hubspot_A | hubspot_B,2
20,james.bailey@clearwavedental.com,A-10012,james.bailey@clearwavedental.com,james.bailey@clearwavedental.com,James,Bailey,Clear Wave Dental,Practice Administrator,Paid Search,SQL,2024-02-21,2024-03-09,2024-03-09,NaT,NaT,Priya Nair,entered manually by marketing,2024-02-21,hubspot_A,1
21,joseph.hamilton@trailheadoutdoor.co,A-10027,joseph.hamilton@trailheadoutdoor.co,joseph.hamilton@trailheadoutdoor.co,Joseph,Hamilton,Trailhead Outdoor Co,People Director,Direct Traffic,Lead,2025-03-22,NaT,NaT,NaT,NaT,Jordan Miles,owner changed after routing,2025-06-22,hubspot_A | hubspot_B,2
22,julian.parker@westfieldtherapy.com,A-10032,julian.parker@westfieldtherapy.com,julian.parker@westfieldtherapy.com,Julian,Parker,Westfield Therapy,Clinic Administrator,Partner,MQL,2024-08-24,2025-03-05,NaT,NaT,NaT,Tina Shah,entered manually by marketing,2025-06-10,hubspot_A | hubspot_B,2
23,layla.ford@unitybehavioral.org,B-20027,layla.ford@unitybehavioral.org,layla.ford@unitybehavioral.org,Layla,Ford,Unity Behavioral Health,HRIS Analyst,referral,Customer,2025-02-24,2025-03-16,2025-04-16,2025-05-20,2025-05-25,Tina Shah,stage synced late,2025-05-11,hubspot_B,1
24,leo.cox@acornchildcare.com,A-10031,leo.cox@acornchildcare.com,leo.cox@acornchildcare.com,Leo,Cox,Acorn Childcare,Founder,Trade Show,Lead,2024-01-26,NaT,NaT,NaT,NaT,Priya Nair,owner changed after routing,2024-03-29,hubspot_A | hubspot_B,2
25,levi.reed@metrobuildservices.com,A-10035,levi.reed@metrobuildservices.com,levi.reed@metrobuildservices.com,Levi,Reed,MetroBuild Services,HR Director,Paid Search,SQL,2025-06-17,2025-06-24,2025-07-11,NaT,NaT,Tina Shah,Jordan updated stage after call,2025-08-05,hubspot_A,1
26,liam.brooks@nexahealth.io,A-10001,liam.brooks@nexahealth.io,liam.brooks@nexahealth.io,Liam,Brooks,NexaHealth,Operations Manager,Referral,Opportunity,2024-02-02,2024-02-14,2024-03-02,2024-03-06,NaT,Tina Shah,owner changed after routing,2024-03-06,hubspot_A | hubspot_B,2
27,luna.butler@crownmedsupply.com,A-10024,luna.butler@crownmedsupply.com,luna.butler@crownmedsupply.com,Luna,Butler,Crown Medical Supply,Recruiting Manager,Paid Search,Opportunity,2025-01-26,2025-02-10,2025-02-24,2025-03-08,NaT,Priya Nair,owner changed after routing,2025-03-09,hubspot_A,1
28,mason.clark@everwellclinics.com,A-10007,mason.clark@everwellclinics.com,mason.clark@everwellclinics.com,Mason,Clark,Everwell Clinics,Controller,Trade Show,SQL,2025-04-14,2025-11-23,2025-05-18,NaT,NaT,Sofia Gomez,possible duplicate from legacy CRM,2025-12-23,hubspot_A | hubspot_B,2
29,matthew.russell@elmstreetfoods.com,A-10023,matthew.russell@elmstreetfoods.com,matthew.russell@elmstreetfoods.com,Matthew,Russell,Elm Street Foods,HR Manager,Paid Search,Opportunity,2024-08-30,2024-09-24,2024-10-05,2024-10-31,NaT,Sofia Gomez,imported from webinar list,2024-09-12,hubspot_A | hubspot_B,2
30,mia.flores@northwindadvisors.com,A-10009,mia.flores@northwindadvisors.com,mia.flores@northwindadvisors.com,Mia,Flores,North Wind Advisors,Director of Finance,Direct Traffic,Opportunity,2024-02-02,2024-02-04,2024-03-07,2024-03-22,NaT,Priya Nair,Jordan updated stage after call,2024-05-15,hubspot_A,1
31,michael.barnes@oakridenp.org,B-20017,michael.barnes@oakridenp.org,michael.barnes@oakridenp.org,Michael,Barnes,Oakridge Nonprofit,Finance Manager,Partner,Lead,2025-04-25,NaT,NaT,NaT,NaT,Marcus Lee,manually entered,2025-05-18,hubspot_B,1
32,noah.reed@stonebridgehr.com,A-10002,noah.reed@stonebridgehr.com,noah.reed@stonebridgehr.com,Noah,Reed,Stonebridge HR,HR Director,Partner,Customer,2024-02-07,2024-02-16,2024-02-13,2024-04-06,2024-05-13,Priya Nair,Jordan updated stage after call,2024-06-02,hubspot_A | hubspot_B,2
33,nora.hayes@bridgewellfinance.com,A-10029,nora.hayes@bridgewellfinance.com,nora.hayes@bridgewellfinance.com,Nora,Hayes,Bridgewell Finance,HR Director,Referral,Customer,2025-02-19,2025-02-19,2025-03-10,2025-08-10,2025-09-22,Sofia Gomez,possible duplicate from legacy CRM,2025-03-18,hubspot_A | hubspot_B,2
34,olivia.chen@harborfg.com,A-10004,olivia.chen@harborfg.com,olivia.chen@harborfg.com,Olivia,Chen,Harbor Financial Grp,Recruiting Lead,Direct Traffic,SQL,2024-04-27,2024-05-14,2024-05-31,NaT,NaT,Tina Shah,MQL date added later,2024-06-30,hubspot_A | hubspot_B,2
35,owen.coleman@atlasautogroup.com,B-20021,owen.coleman@atlasautogroup.com,owen.coleman@atlasautogroup.com,Owen,Coleman,Atlas Auto Group,GM,Event,Lead,2025-08-16,NaT,NaT,NaT,NaT,Ben Carter,manually entered,2025-11-28,hubspot_B,1
36,penelope.stewart@cloudnine-tech.io,A-10033,penelope.stewart@cloudnine-tech.io,penelope.stewart@cloudnine-tech.io,Penelope,Stewart,CloudNine Tech,Director People,Direct Traffic,<NA>,2024-05-04,2024-05-29,NaT,NaT,NaT,Sofia Gomez,MQL date added later,2024-08-26,hubspot_A,1
37,riley.peterson@harborlinetransit.com,A-10034,riley.peterson@harborlinetransit.com,riley.peterson@harborlinetransit.com,Riley,Peterson,Harborline Transit,Safety Director,Trade Show,MQL,2025-05-31,2025-06-17,NaT,NaT,NaT,Marcus Lee,stage synced late,2025-09-06,hubspot_A | hubspot_B,2
38,samuel.myers@corelinepackaging.com,A-10028,samuel.myers@corelinepackaging.com,samuel.myers@corelinepackaging.com,Samuel,Myers,Coreline Packaging,Finance Director,Partner,SQL,2024-03-01,2024-11-24,2024-12-20,NaT,NaT,Ben Carter,Jordan updated stage after call,2024-12-11,hubspot_A | hubspot_B,2
39,scarlett.long@heliomedia.co,A-10018,scarlett.long@heliomedia.co,scarlett.long@heliomedia.co,Scarlett,Long,Helio Media,Revenue Operations Manager,Organic Search,Customer,2024-09-22,2024-10-10,2024-10-11,2024-11-23,2025-01-17,Jordan Miles,imported from webinar list,2025-06-27,hubspot_A | hubspot_B,2
40,sebastian.powell@wellrootrx.com,B-20019,sebastian.powell@wellrootrx.com,sebastian.powell@wellrootrx.com,Sebastian,Powell,WellRoot Pharmacy,HRBP,referral,MQL,2025-01-22,2025-02-01,NaT,NaT,NaT,Jordan Miles,duplicate suspected,2025-03-27,hubspot_B,1
41,sophia.james@bluepeaksoft.com,A-10006,sophia.james@bluepeaksoft.com,sophia.james@bluepeaksoft.com,Sophia,James,Blue Peak Software,HRBP,Partner,Opportunity,2024-12-16,2024-12-28,2025-01-22,2025-03-06,NaT,Tina Shah,duplicate suspected,2025-01-22,hubspot_A | hubspot_B,2
42,victoria.simmons@silverlaketelecom.com,A-10022,victoria.simmons@silverlaketelecom.com,victoria.simmons@silverlaketelecom.com,Victoria,Simmons,SilverLake Telecom,Comp & Benefits Manager,Trade Show,Customer,2024-05-06,2024-05-09,2025-02-04,2025-02-26,2025-03-14,Tina Shah,MQL date added later,2025-05-06,hubspot_A | hubspot_B,2
43,wyatt.morris@cedarstonehospitality.com,B-20034,wyatt.morris@cedarstonehospitality.com,wyatt.morris@cedarstonehospitality.com,Wyatt,Morris,Cedarstone Hospitality,Regional GM,Event,Lead,2024-04-18,NaT,NaT,NaT,NaT,Sofia Gomez,stage synced late,2024-06-24,hubspot_B,1
44,zoey.cole@urbansparkcreative.com,A-10030,zoey.cole@urbansparkcreative.com,zoey.cole@urbansparkcreative.com,Zoey,Cole,UrbanSpark Creative,Office Manager,Direct Traffic,SQL,2024-11-08,2025-07-02,2025-07-12,NaT,NaT,Tina Shah,Jordan updated stage after call,2025-06-25,hubspot_A | hubspot_B,2